Namespace pepeizq.Editor.pepeizqdeals
    Module Desarrolladores

        Public Sub GenerarDatos()

            Dim listaPublishers As List(Of Clases.Desarrolladores) = CargarLista()

            Dim frame As Frame = Window.Current.Content
            Dim pagina As Page = frame.Content

            Dim cb As ComboBox = pagina.FindName("cbEditorTitulopepeizqdealsPublishers")
            cb.Items.Clear()

            cb.Items.Add("--")

            If listaPublishers.Count > 0 Then
                For Each publisher In listaPublishers
                    Dim tb As New TextBlock With {
                        .Text = publisher.Publisher,
                        .Tag = publisher
                    }

                    cb.Items.Add(tb)
                Next
            End If

            cb.SelectedIndex = 0

            AddHandler cb.SelectionChanged, AddressOf CambiarDatos

        End Sub

        Private Sub CambiarDatos(sender As Object, e As SelectionChangedEventArgs)

            Dim frame As Frame = Window.Current.Content
            Dim pagina As Page = frame.Content

            Dim cb As ComboBox = sender

            Dim tbTitulo As TextBox = pagina.FindName("tbEditorTitulopepeizqdeals")

            If Not cb.SelectedIndex = 0 Then
                Dim publisher As TextBlock = cb.SelectedItem

                If Not publisher Is Nothing Then
                    Dim publisher2 As Clases.Desarrolladores = publisher.Tag

                    If Not tbTitulo.Text = Nothing Then
                        If tbTitulo.Text.Contains("Sale") Then
                            If Not publisher2 Is Nothing Then
                                If Not tbTitulo.Text.Contains(publisher2.Publisher) Then
                                    tbTitulo.Text = publisher2.Publisher + " " + tbTitulo.Text
                                End If
                            End If
                        End If
                    End If

                    If Not publisher2.Logo = Nothing Then
                        Dim tbImagen As TextBox = pagina.FindName("tbEditorTitulopepeizqdealsPublishersImagen")
                        tbImagen.Text = publisher2.Logo
                    End If
                End If
            End If

        End Sub

        Private Function CargarLista()

            Dim lista As New List(Of Clases.Desarrolladores) From {
                New Clases.Desarrolladores("10tons", "@10tonsLtd", Nothing),
                New Clases.Desarrolladores("11 bit studios", "@11bitstudios", Nothing),
                New Clases.Desarrolladores("1C Company", "@1C_Company", Nothing),
                New Clases.Desarrolladores("1CC Games", "@1CCGames", Nothing),
                New Clases.Desarrolladores("2K", "@2K", Nothing),
                New Clases.Desarrolladores("2 Zombie Games", "@2zombiegames", Nothing),
                New Clases.Desarrolladores("34BigThings", "@34bigthings", Nothing),
                New Clases.Desarrolladores("3D Avenue", "@3D_Avenue", Nothing),
                New Clases.Desarrolladores("3DClouds.it", "@3DClouds", Nothing),
                New Clases.Desarrolladores("505 Games", "@505_Games", Nothing),
                New Clases.Desarrolladores("Abbey Games", "@AbbeyGamesNL", Nothing),
                New Clases.Desarrolladores("Abylight Studios", "@abylight", Nothing),
                New Clases.Desarrolladores("ACE Team", "@theACETeam", Nothing),
                New Clases.Desarrolladores("Adliberum", "@liamtwose", Nothing),
                New Clases.Desarrolladores("Adult Swim", "@adultswimgames", Nothing),
                New Clases.Desarrolladores("AdroVGames", "@adrovgames", Nothing),
                New Clases.Desarrolladores("Aerosoft", "@AerosoftGmbH", Nothing),
                New Clases.Desarrolladores("Akupara Games", "@akuparagames", Nothing),
                New Clases.Desarrolladores("Aksys Games", "@aksysgames", Nothing),
                New Clases.Desarrolladores("ALICE IN DISSONANCE", "@projectwritten", Nothing),
                New Clases.Desarrolladores("Alientrap", "@AlientrapGames", Nothing),
                New Clases.Desarrolladores("Amanita Design", "@Amanita_Design", Nothing),
                New Clases.Desarrolladores("Ammobox Studios", "@ammoboxstudios", Nothing),
                New Clases.Desarrolladores("Amplitude Studios", "@Amplitude", Nothing),
                New Clases.Desarrolladores("Analgesic Productions", "@analgesicprod", Nothing),
                New Clases.Desarrolladores("Ankama", "@AnkamaGames", Nothing),
                New Clases.Desarrolladores("Annapurna Interactive", "@A_i", Nothing),
                New Clases.Desarrolladores("Another Indie", "@AnotherIndieS", Nothing),
                New Clases.Desarrolladores("Applava", "@Applava", Nothing),
                New Clases.Desarrolladores("Auroch Digital", "@AurochDigital", Nothing),
                New Clases.Desarrolladores("Autarca", "@AutarcaDev", Nothing),
                New Clases.Desarrolladores("Arc System Works", "@ArcSystemWorksU", Nothing),
                New Clases.Desarrolladores("Arcen Games", "@ArcenGames", Nothing),
                New Clases.Desarrolladores("Argent Games", "@argent_games", Nothing),
                New Clases.Desarrolladores("Artifex Mundi", "@ArtifexMundi", Nothing),
                New Clases.Desarrolladores("Aslan Game Studio", "@AslanGameStudio", Nothing),
                New Clases.Desarrolladores("Asmodee Digital", "@AsmodeeDigital", Nothing),
                New Clases.Desarrolladores("Aspyr", "@AspyrMedia", Nothing),
                New Clases.Desarrolladores("astragon Entertainment", "@astragon_GmbH", Nothing),
                New Clases.Desarrolladores("Atelier 801", "@Atelier801", Nothing),
                New Clases.Desarrolladores("Atomic Fabrik", "@atomicfabrik", Nothing),
                New Clases.Desarrolladores("Avalanche Studio", "@AvalancheSweden", Nothing),
                New Clases.Desarrolladores("Awesome Games Studio", "@AwesomeGamesStd", Nothing),
                New Clases.Desarrolladores("B Negative Games", "@BNegativeGames", Nothing),
                New Clases.Desarrolladores("Bandai Namco", "@BandaiNamcoEU", "Assets\Publishers\bandainamco.png"),
                New Clases.Desarrolladores("BattleGoat Studios", "@BattleGoat", Nothing),
                New Clases.Desarrolladores("Beamdog", "@BeamdogInc", Nothing),
                New Clases.Desarrolladores("BeautiFun Games", "@BeautiFunGames", Nothing),
                New Clases.Desarrolladores("Bedtime Digital Games", "@BedtimeDG", Nothing),
                New Clases.Desarrolladores("Benerot", "@BenerotCompany", Nothing),
                New Clases.Desarrolladores("Bethesda", "@bethesda", Nothing),
                New Clases.Desarrolladores("Betadwarf", "@BetaDwarf", Nothing),
                New Clases.Desarrolladores("Big Robot Ltd", "@BigRobotLtd", Nothing),
                New Clases.Desarrolladores("Big Evil Corp", "@Big_Evil_Corp", Nothing),
                New Clases.Desarrolladores("Bigben Games", "@Bigben_games", Nothing),
                New Clases.Desarrolladores("Bigosaur", "@Bigosaur", Nothing),
                New Clases.Desarrolladores("Bishop Games", "@BishopGamesTeam", Nothing),
                New Clases.Desarrolladores("Bitbox", "@LifeisFeudal", Nothing),
                New Clases.Desarrolladores("Black Icicles", "@BlackIceTheGame", Nothing),
                New Clases.Desarrolladores("Black Forest Games", "@BlackForestTeam", Nothing),
                New Clases.Desarrolladores("BLACK LODGE GAMES", "@BlackLodgeGames", Nothing),
                New Clases.Desarrolladores("BlackEye Games", "@GloriaVictisMMO", Nothing),
                New Clases.Desarrolladores("Blacklight Interactive", "@BlackLightInt", Nothing),
                New Clases.Desarrolladores("BlackMill Games", "@BlackMillGame", Nothing),
                New Clases.Desarrolladores("Blazing Griffin", "@BlazingGriffin", Nothing),
                New Clases.Desarrolladores("Blazing Planet", "@Blazing_Planet", Nothing),
                New Clases.Desarrolladores("Bleank", "@Bleank", Nothing),
                New Clases.Desarrolladores("Blendo Games", "@BlendoGames", Nothing),
                New Clases.Desarrolladores("Blue Bottle Games", "@dcfedor", Nothing),
                New Clases.Desarrolladores("Blue Isle Studios", "@BlueIsleStudio", Nothing),
                New Clases.Desarrolladores("Bohemia Interactive", "@bohemiainteract", Nothing),
                New Clases.Desarrolladores("Brace Yourself Games", "@BYG_Vancouver", Nothing),
                New Clases.Desarrolladores("Brilliant Game Studios", "@BrilliantGames", Nothing),
                New Clases.Desarrolladores("BT Studios", "@btstudiosgames", Nothing),
                New Clases.Desarrolladores("Buka Entertainment", "@Buka_Ent_Games", Nothing),
                New Clases.Desarrolladores("BURA", "@lgdays", Nothing),
                New Clases.Desarrolladores("Butterscotch", "@BScotchShenani", Nothing),
                New Clases.Desarrolladores("Capcom", "@CapcomUSA_", Nothing),
                New Clases.Desarrolladores("Capybara Games", "@CAPYGAMES", Nothing),
                New Clases.Desarrolladores("Carbon Games", "@CB_Sword", Nothing),
                New Clases.Desarrolladores("Cardboard Sword", "@CarbonGames", Nothing),
                New Clases.Desarrolladores("Cat Nigiri", "@CatNigiri", Nothing),
                New Clases.Desarrolladores("CCP Games", "@CCPGames", Nothing),
                New Clases.Desarrolladores("CCCP-games", "@LeCCCP", Nothing),
                New Clases.Desarrolladores("CD PROJEKT RED", "@CDPROJEKTRED", Nothing),
                New Clases.Desarrolladores("Cellar Door Games", "@CellarDoorGames", Nothing),
                New Clases.Desarrolladores("Chasing Carrots", "@Chasing_Carrots", Nothing),
                New Clases.Desarrolladores("Choice of Games", "@choiceofgames", Nothing),
                New Clases.Desarrolladores("Chucklefish", "@ChucklefishLTD", Nothing),
                New Clases.Desarrolladores("CI Games", "@CIGamesOfficial", Nothing),
                New Clases.Desarrolladores("CINEMAX GAMES", "@CINEMAXGAMES", Nothing),
                New Clases.Desarrolladores("Clapfoot", "@foxholegame", Nothing),
                New Clases.Desarrolladores("CleanWaterSoft", "@CleanWaterSoft", Nothing),
                New Clases.Desarrolladores("Clever Endeavour", "@ClevEndeavGames", Nothing),
                New Clases.Desarrolladores("Clickteam", "@Clickteam", Nothing),
                New Clases.Desarrolladores("Clifftop Games", "@ClifftopGames", Nothing),
                New Clases.Desarrolladores("Cloudhead Games", "@CloudheadGames", Nothing),
                New Clases.Desarrolladores("CoaguCo Industries", "@CoaguCo", Nothing),
                New Clases.Desarrolladores("Cockroach Inc", "@theDreamGame", Nothing),
                New Clases.Desarrolladores("Codemasters", "@Codemasters", Nothing),
                New Clases.Desarrolladores("Codename Entertainment", "@CodenameEnt", Nothing),
                New Clases.Desarrolladores("Coffee Stain", "@Coffee_Stain", Nothing),
                New Clases.Desarrolladores("Cold Beam Games", "@ColdBeamGames", Nothing),
                New Clases.Desarrolladores("Coldwild Games", "@ColdwildGames", Nothing),
                New Clases.Desarrolladores("ConcernedApe", "@ConcernedApe", Nothing),
                New Clases.Desarrolladores("Copychaser Games", "@bengelinas", Nothing),
                New Clases.Desarrolladores("Cosmo D Studios", "@cosmoddd", Nothing),
                New Clases.Desarrolladores("COWCAT Games", "@COWCATGames", Nothing),
                New Clases.Desarrolladores("CrackedGhost", "@realCGG", Nothing),
                New Clases.Desarrolladores("Crackshell", "@RealCrackshell", Nothing),
                New Clases.Desarrolladores("Crate Entertainment", "@GrimDawn", Nothing),
                New Clases.Desarrolladores("Crazy Monkey Studios", "@CrazyMonkeyStu", Nothing),
                New Clases.Desarrolladores("Croteam", "@Croteam", Nothing),
                New Clases.Desarrolladores("Crows Crows Crows", "@crowsx3", Nothing),
                New Clases.Desarrolladores("Crytek", "@Crytek", Nothing),
                New Clases.Desarrolladores("Crytivo", "@Crytivo", Nothing),
                New Clases.Desarrolladores("Curve Digital", "@CurveDigital", "Assets\Publishers\curvedigital.png"),
                New Clases.Desarrolladores("Cyan Worlds Inc", "@cyanworlds", Nothing),
                New Clases.Desarrolladores("Cyanide Studio", "@CyanideStudio", Nothing),
                New Clases.Desarrolladores("CyberCoconut", "@TWLgame", Nothing),
                New Clases.Desarrolladores("D-Pad Studio", "@DPadStudio", Nothing),
                New Clases.Desarrolladores("D3 PUBLISHER", "@D3_PUBLISHER", Nothing),
                New Clases.Desarrolladores("Daedalic", "@daedalic", Nothing),
                New Clases.Desarrolladores("DANGEN Entertainment", "@Dangen_Ent", Nothing),
                New Clases.Desarrolladores("Daniel Mullins Games", "@DMullinsGames", Nothing),
                New Clases.Desarrolladores("David Stark", "@zarkonnen_com", Nothing),
                New Clases.Desarrolladores("Daylight-Studios", "@holypotatogame", Nothing),
                New Clases.Desarrolladores("Deadpan Games", "@onegamewill", Nothing),
                New Clases.Desarrolladores("DECK13 Interactive", "@Deck13_de", Nothing),
                New Clases.Desarrolladores("Deckpoint Studio", "@LucklessSeven", Nothing),
                New Clases.Desarrolladores("Deep Silver", "@deepsilver", "Assets\Publishers\deepsilver.png"),
                New Clases.Desarrolladores("Degica", "@DegicaGames", Nothing),
                New Clases.Desarrolladores("Destructive Creations", "@DestCreat_Team", Nothing),
                New Clases.Desarrolladores("Devilish Games", "@devilishgames", Nothing),
                New Clases.Desarrolladores("Devolver Digital", "@devolverdigital", Nothing),
                New Clases.Desarrolladores("Digital Cybercherries", "@DCybercherries", Nothing),
                New Clases.Desarrolladores("Digital Extremes", "@PlayWarframe", Nothing),
                New Clases.Desarrolladores("Digital Tribe", "@dTribeGames", Nothing),
                New Clases.Desarrolladores("DigitalEZ", "@digitalezstudio", Nothing),
                New Clases.Desarrolladores("Digitalmindsoft", "@digitalmindsoft", Nothing),
                New Clases.Desarrolladores("Dinosaur Polo Club", "@dinopoloclub", Nothing),
                New Clases.Desarrolladores("DireWolfDigital", "@direwolfdigital", Nothing),
                New Clases.Desarrolladores("DLsite", "@DLsite", Nothing),
                New Clases.Desarrolladores("Dodge Roll", "@DodgeRollGames", Nothing),
                New Clases.Desarrolladores("Dotemu", "@Dotemu", Nothing),
                New Clases.Desarrolladores("Double Eleven LTD", "@DoubleElevenLtd", Nothing),
                New Clases.Desarrolladores("Double Fine", "@DoubleFine", Nothing),
                New Clases.Desarrolladores("Double Stallion Games", "@dblstallion", Nothing),
                New Clases.Desarrolladores("DoubleBear Productions", "@DoubleBearGames", Nothing),
                New Clases.Desarrolladores("DoubleDutch Games", "@dd_games", Nothing),
                New Clases.Desarrolladores("Dovetail Games", "@dovetailgames", Nothing),
                New Clases.Desarrolladores("Draknek", "@Draknek", Nothing),
                New Clases.Desarrolladores("Dreamloop Games", "@DreamloopGames", Nothing),
                New Clases.Desarrolladores("DrinkBox Studios", "@DrinkBoxStudios", Nothing),
                New Clases.Desarrolladores("DRM GMZ", "@__LCN__", Nothing),
                New Clases.Desarrolladores("Drool LLC", "@ThumperGame", Nothing),
                New Clases.Desarrolladores("DRUNKEN APES GAMES", "@DrunkenApes", Nothing),
                New Clases.Desarrolladores("Dry Cactus", "@drycactusgames", Nothing),
                New Clases.Desarrolladores("ds-sans", "@dssansVN", Nothing),
                New Clases.Desarrolladores("DYA Games", "@DYAGames", Nothing),
                New Clases.Desarrolladores("Eat Create Sleep", "@EatCreateSleep", Nothing),
                New Clases.Desarrolladores("ebi-hime", "@ebihimes", Nothing),
                New Clases.Desarrolladores("Egosoft", "@EGOSOFT", Nothing),
                New Clases.Desarrolladores("Eidos Montréal", "@EidosMontreal", Nothing),
                New Clases.Desarrolladores("Ellada Games", "@ElladaGames", Nothing),
                New Clases.Desarrolladores("Endless Loop Studios", "@EndlessLoopStd", Nothing),
                New Clases.Desarrolladores("EnsenaSoft", "@ensenasoft", Nothing),
                New Clases.Desarrolladores("Epic Games", "@EpicGames", "Assets\Publishers\epicgames.png"),
                New Clases.Desarrolladores("Epopeia Games", "@epopeiagames", Nothing),
                New Clases.Desarrolladores("EQ Studios", "@EQSLV", Nothing),
                New Clases.Desarrolladores("Eugen Systems", "@EugenSystems", Nothing),
                New Clases.Desarrolladores("Ertal Games", "@ertal77", Nothing),
                New Clases.Desarrolladores("Event Horizon", "@EventHorizonDev", Nothing),
                New Clases.Desarrolladores("EvilCoGames", "@EvilCoGames", Nothing),
                New Clases.Desarrolladores("Excalibur Games", "@Excalpublishing", Nothing),
                New Clases.Desarrolladores("Exor Studios", "@EXORStudios", Nothing),
                New Clases.Desarrolladores("Fabraz", "@Fabrazz", Nothing),
                New Clases.Desarrolladores("Failbetter Games", "@failbettergames", Nothing),
                New Clases.Desarrolladores("Fantasy Grounds", "@FantasyGrounds2", Nothing),
                New Clases.Desarrolladores("Farom Studio", "@StudioFarom", Nothing),
                New Clases.Desarrolladores("Farsky Interactive", "@FarskyInt", Nothing),
                New Clases.Desarrolladores("Faster Time Games", "@FasterTimeGames", Nothing),
                New Clases.Desarrolladores("Fatshark", "@fatsharkgames", Nothing),
                New Clases.Desarrolladores("Fellow Traveller", "@FellowTravellr", Nothing),
                New Clases.Desarrolladores("FIFTYTWO", "@wefiftytwo", Nothing),
                New Clases.Desarrolladores("Finji", "@FinjiCo", Nothing),
                New Clases.Desarrolladores("Firaxis Games", "@FiraxisGames", Nothing),
                New Clases.Desarrolladores("Firefly Studios", "@fireflyworlds", Nothing),
                New Clases.Desarrolladores("Fireproof Games", "@Fireproof_Games", Nothing),
                New Clases.Desarrolladores("Fishing Cactus", "@FishingCactus", Nothing),
                New Clases.Desarrolladores("Flashbulb", "@flashbulbgames", Nothing),
                New Clases.Desarrolladores("Flying Interactive", "@FlyingInt", Nothing),
                New Clases.Desarrolladores("Focus Home", "@FocusHome", Nothing),
                New Clases.Desarrolladores("Forgotten Empires", "@ForgottenEmp", Nothing),
                New Clases.Desarrolladores("Freebird Games", "@Reives_Freebird", Nothing),
                New Clases.Desarrolladores("Freejam", "@Freejamgames", Nothing),
                New Clases.Desarrolladores("FreezeNova Games", "@FreezeNova", Nothing),
                New Clases.Desarrolladores("Frictional Games", "@frictionalgames", Nothing),
                New Clases.Desarrolladores("Frogwares", "@Frogwares", Nothing),
                New Clases.Desarrolladores("Frontier Developments", "@frontierdev", Nothing),
                New Clases.Desarrolladores("Frontwing USA", "@FrontwingInt", Nothing),
                New Clases.Desarrolladores("Frozenbyte", "@Frozenbyte", Nothing),
                New Clases.Desarrolladores("Fruitbat Factory", "@FruitbatFactory", Nothing),
                New Clases.Desarrolladores("Fun Bits Interactive", "@SquidsFromSpace", Nothing),
                New Clases.Desarrolladores("Funbox Media", "@FunboxMediaLtd", Nothing),
                New Clases.Desarrolladores("Funcom", "@funcom", Nothing),
                New Clases.Desarrolladores("Funktronic Labs", "@funktroniclabs", Nothing),
                New Clases.Desarrolladores("Gambrinous", "@gambrinous", Nothing),
                New Clases.Desarrolladores("Gameconnect", "@gameconnectnet", Nothing),
                New Clases.Desarrolladores("Gamepires", "@Gamepires", Nothing),
                New Clases.Desarrolladores("Gamera Interactive", "@gameragamesint", Nothing),
                New Clases.Desarrolladores("Games Operators", "@GamesOperators", Nothing),
                New Clases.Desarrolladores("Gato Salvaje S.L.", "@GatoSalvajeDEV", Nothing),
                New Clases.Desarrolladores("GB Patch Games", "@Patch_Games", Nothing),
                New Clases.Desarrolladores("Gears for Breakfast", "@HatInTime", Nothing),
                New Clases.Desarrolladores("GFX47 Games", "@GFX47", Nothing),
                New Clases.Desarrolladores("Ghost Ship Games", "@JoinDeepRock", Nothing),
                New Clases.Desarrolladores("GIANTS Software", "@GIANTSSoftware", Nothing),
                New Clases.Desarrolladores("Glaiel Games", "@TylerGlaiel", Nothing),
                New Clases.Desarrolladores("Glitchers", "@glitchers", Nothing),
                New Clases.Desarrolladores("GoblinzStudio", "@studio_goblinz", Nothing),
                New Clases.Desarrolladores("Gutter Arcade", "@GutterArcade", Nothing),
                New Clases.Desarrolladores("Green Man Gaming", "@gmg_publishing", Nothing),
                New Clases.Desarrolladores("Greenheart Games", "@GreenheartGames", Nothing),
                New Clases.Desarrolladores("Grey Alien Games", "@GreyAlien", Nothing),
                New Clases.Desarrolladores("Grip Digital", "@Grip_Digital", Nothing),
                New Clases.Desarrolladores("Groupees", "@groupees1", Nothing),
                New Clases.Desarrolladores("HakJak", "@HakJakGames", Nothing),
                New Clases.Desarrolladores("Hammer&Ravens", "@Ham_Rav", Nothing),
                New Clases.Desarrolladores("Hanako Games", "@HanakoGames", Nothing),
                New Clases.Desarrolladores("HandyGames", "@handy_games", Nothing),
                New Clases.Desarrolladores("Headup Games", "@HeadupGames", Nothing),
                New Clases.Desarrolladores("Heart Shaped Games", "@heartshapedgame", Nothing),
                New Clases.Desarrolladores("Hello Bard", "@hellobard", Nothing),
                New Clases.Desarrolladores("Hemisphere Games", "@HemisphereGames", Nothing),
                New Clases.Desarrolladores("HeR Interactive", "@HerInteractive", Nothing),
                New Clases.Desarrolladores("Hero Concept", "@doughlings", Nothing),
                New Clases.Desarrolladores("Hidden Path Entertainment", "@HiddenPathEnt", Nothing),
                New Clases.Desarrolladores("HIKARI FIELD", "@hikari_field", Nothing),
                New Clases.Desarrolladores("Hinterland Studio", "@HinterlandGames", Nothing),
                New Clases.Desarrolladores("HOF Studios", "@depthextinction", Nothing),
                New Clases.Desarrolladores("Hollow Ponds", "@hllwpnds", Nothing),
                New Clases.Desarrolladores("Holospark Games", "@holo_spark", Nothing),
                New Clases.Desarrolladores("Hoplon Infotainment", "@HMM_Hoplon_EN", Nothing),
                New Clases.Desarrolladores("Humble Bundle", "@humble", Nothing),
                New Clases.Desarrolladores("HypeTrain Digital", "@HypeTrainD", Nothing),
                New Clases.Desarrolladores("Ice-Pick Lodge", "@IcePickLodge", Nothing),
                New Clases.Desarrolladores("Iceberg", "@Iceberg_Int", Nothing),
                New Clases.Desarrolladores("IDALGAME", "@IDALGAME", Nothing),
                New Clases.Desarrolladores("Idea Factory", "@IdeaFactoryIntl", Nothing),
                New Clases.Desarrolladores("Igloo Studio", "@bountybrawlgame", Nothing),
                New Clases.Desarrolladores("Image & Form", "@ImageForm", Nothing),
                New Clases.Desarrolladores("ImaginationOverflow", "@ImaginationOver", Nothing),
                New Clases.Desarrolladores("Imperium42 Game Studio", "@TheThroneOfLies", Nothing),
                New Clases.Desarrolladores("INDIECODE GAMES", "@INDIECODE_GAMES", Nothing),
                New Clases.Desarrolladores("IndieGala", "@IndieGala", Nothing),
                New Clases.Desarrolladores("inkle", "@inkleStudios", Nothing),
                New Clases.Desarrolladores("Interactive Stone", "@StoneInteract", Nothing),
                New Clases.Desarrolladores("Introversion Software", "@IVSoftware", Nothing),
                New Clases.Desarrolladores("InvertMouse", "@InvertMouse", Nothing),
                New Clases.Desarrolladores("ION LANDS", "@ionlands", Nothing),
                New Clases.Desarrolladores("Jackbox Games", "@jackboxgames", Nothing),
                New Clases.Desarrolladores("jandusoft", "@JanduSoft", Nothing),
                New Clases.Desarrolladores("JAST", "@jastusa", Nothing),
                New Clases.Desarrolladores("JForce Games", "@JForceGames", Nothing),
                New Clases.Desarrolladores("JIW-Games", "@JIWGames", Nothing),
                New Clases.Desarrolladores("Johnny Ginard", "@johnnyginard", Nothing),
                New Clases.Desarrolladores("Jolly Crouton Media", "@jollycrouton", Nothing),
                New Clases.Desarrolladores("Jundroo", "@JundrooGames", Nothing),
                New Clases.Desarrolladores("Kagura Games", "@KaguraGaming", Nothing),
                New Clases.Desarrolladores("Kaleido Games", "@KaleidoGames", Nothing),
                New Clases.Desarrolladores("Kalypso", "@kalypsomediausa", Nothing),
                New Clases.Desarrolladores("Kasedo Games", "@KasedoGames", Nothing),
                New Clases.Desarrolladores("Katta Games", "@asteroidfight", Nothing),
                New Clases.Desarrolladores("Kenomica Productions", "@KenomicaPro", Nothing),
                New Clases.Desarrolladores("KillHouse Games", "@inthekillhouse", Nothing),
                New Clases.Desarrolladores("Kitfox Games", "@KitfoxGames", Nothing),
                New Clases.Desarrolladores("Klei", "@klei", Nothing),
                New Clases.Desarrolladores("Knuckle Cracker", "@knucracker", Nothing),
                New Clases.Desarrolladores("Konami", "@Konami", Nothing),
                New Clases.Desarrolladores("Kongregate", "@kongregate", Nothing),
                New Clases.Desarrolladores("Konstructors Entertainment", "@konstructors", Nothing),
                New Clases.Desarrolladores("Kozinaka Labs", "@insatiagame", Nothing),
                New Clases.Desarrolladores("L3O", "@L3O_Interactive", Nothing),
                New Clases.Desarrolladores("LAME Dimension", "@ChairGTables", Nothing),
                New Clases.Desarrolladores("Lantana Games", "@lantanagames", Nothing),
                New Clases.Desarrolladores("Laundry Bear Games", "@laundry_bear", Nothing),
                New Clases.Desarrolladores("Larian Studios", "@larianstudios", Nothing),
                New Clases.Desarrolladores("League of Geeks", "@ArmelloGame", Nothing),
                New Clases.Desarrolladores("League of Sweat", "@League_of_Sweat", Nothing),
                New Clases.Desarrolladores("Lo-Fi Games", "@KenshiOfficial", Nothing),
                New Clases.Desarrolladores("Loiste Interactive", "@LoisteInteract", Nothing),
                New Clases.Desarrolladores("Longbow Games", "@LongbowGames", Nothing),
                New Clases.Desarrolladores("Loren Lemcke", "@LorenLemcke", Nothing),
                New Clases.Desarrolladores("Lightning Rod Games", "@LRGthunder", Nothing),
                New Clases.Desarrolladores("Lince Works", "@LinceWorks", Nothing),
                New Clases.Desarrolladores("Lion Shield Studios", "@kingdomscastles", Nothing),
                New Clases.Desarrolladores("Logic Artists", "@LogicArtists", Nothing),
                New Clases.Desarrolladores("Lucid Games Ltd", "@LucidGamesLtd", Nothing),
                New Clases.Desarrolladores("luden.io", "@luden_io", Nothing),
                New Clases.Desarrolladores("Lupiesoft", "@Lupiesoft", Nothing),
                New Clases.Desarrolladores("M2H", "@M2Hgames", Nothing),
                New Clases.Desarrolladores("Mad Gear Games", "@MadGearGames", Nothing),
                New Clases.Desarrolladores("Make Real", "@MakeRealVR", Nothing),
                New Clases.Desarrolladores("Mandragora Studio", "@MandragoraTeam", Nothing),
                New Clases.Desarrolladores("MangaGamer", "@MangaGamer", Nothing),
                New Clases.Desarrolladores("Mango Protocol", "@MangoProtocol", Nothing),
                New Clases.Desarrolladores("Manufacture 43", "@manufacture_43", Nothing),
                New Clases.Desarrolladores("Marcelo Barbosa", "@tchecoforevis", Nothing),
                New Clases.Desarrolladores("MarineVerse", "@MarineVerseVR", Nothing),
                New Clases.Desarrolladores("Marmalade Game Studio", "@MarmaladeGames", Nothing),
                New Clases.Desarrolladores("Marvelous Europe", "@marvelous_games", Nothing),
                New Clases.Desarrolladores("Massive Damage", "@Massive_Damage", Nothing),
                New Clases.Desarrolladores("MasterCalamity", "@master_calamity", Nothing),
                New Clases.Desarrolladores("Matt Glanville", "@crowbarska", Nothing),
                New Clases.Desarrolladores("Mechanical Boss", "@MechanicalBoss", Nothing),
                New Clases.Desarrolladores("Meridian4", "@Meridian4", Nothing),
                New Clases.Desarrolladores("messhof", "@messhof", Nothing),
                New Clases.Desarrolladores("Mi-Clos Studio", "@Mi_Clos", Nothing),
                New Clases.Desarrolladores("Micropsia Games", "@micropsiagames", Nothing),
                New Clases.Desarrolladores("Midgar Studio", "@MidgarStudio", Nothing),
                New Clases.Desarrolladores("mif2000", "@mif2000", Nothing),
                New Clases.Desarrolladores("Might & Delight", "@MightAndDelight", Nothing),
                New Clases.Desarrolladores("Milkstone Studios", "@milkstone", Nothing),
                New Clases.Desarrolladores("Mimimi", "@MimimiProd", Nothing),
                New Clases.Desarrolladores("MinskWorks", "@MinskWorks", Nothing),
                New Clases.Desarrolladores("Mixed Realms", "@sairentovr", Nothing),
                New Clases.Desarrolladores("Mode 7 Games", "@mode7games", Nothing),
                New Clases.Desarrolladores("Modern Storyteller", "@ModnStoryteller", Nothing),
                New Clases.Desarrolladores("Modii Games", "@modiigames", Nothing),
                New Clases.Desarrolladores("Mohawk Games", "@mohawkgames", Nothing),
                New Clases.Desarrolladores("Monolith Productions", "@MonolithDev", Nothing),
                New Clases.Desarrolladores("Monomi Park", "@monomipark", Nothing),
                New Clases.Desarrolladores("Monstrum Games", "@monstersden", Nothing),
                New Clases.Desarrolladores("Motion Twin", "@motiontwin", Nothing),
                New Clases.Desarrolladores("Mystery Corgi", "@MysteryCorgi", Nothing),
                New Clases.Desarrolladores("Nadeo", "@Maniaplanet", Nothing),
                New Clases.Desarrolladores("Nami Tentou", "@NAMITENTOU", Nothing),
                New Clases.Desarrolladores("narayana games", "@jashan", Nothing),
                New Clases.Desarrolladores("Ndemic Creations", "@NdemicCreations", Nothing),
                New Clases.Desarrolladores("neko.works", "@bakanekofr", Nothing),
                New Clases.Desarrolladores("NetherRealm Studios", "@NetherRealm", Nothing),
                New Clases.Desarrolladores("New Blood Interactive", "@TheNewBloods", Nothing),
                New Clases.Desarrolladores("NewWestGames", "@NewWestGames", Nothing),
                New Clases.Desarrolladores("Nezon Production", "@NezonProduction", Nothing),
                New Clases.Desarrolladores("Nickervision Studios", "@nickervision", Nothing),
                New Clases.Desarrolladores("Night Dive Studios", "@NightdiveStudio", Nothing),
                New Clases.Desarrolladores("Ninja Kiwi Games", "@ninjakiwigames", Nothing),
                New Clases.Desarrolladores("Ninja Theory", "@NinjaTheory", Nothing),
                New Clases.Desarrolladores("NIS America", "@NISAmerica", Nothing),
                New Clases.Desarrolladores("No More Robots", "@nomorerobotshq", Nothing),
                New Clases.Desarrolladores("No Goblin", "@no_goblin", Nothing),
                New Clases.Desarrolladores("Nomad Games", "@Nomadgames", Nothing),
                New Clases.Desarrolladores("Nonadecimal Creative", "@Nonadecimal", Nothing),
                New Clases.Desarrolladores("Ntroy", "@PDO2online", Nothing),
                New Clases.Desarrolladores("Nyamyam", "@nyamyamgames", Nothing),
                New Clases.Desarrolladores("Nyu Media", "@nyumedia", Nothing),
                New Clases.Desarrolladores("Oasis Games", "@OAS_Games", Nothing),
                New Clases.Desarrolladores("Obsidian Entertainment", "@obsidian", Nothing),
                New Clases.Desarrolladores("Oddworld Inhabitants", "@OddworldInc", Nothing),
                New Clases.Desarrolladores("Ogre Head Studio", "@OgreHeadstudio", Nothing),
                New Clases.Desarrolladores("OhNooStudio", "@OhNooStudio", Nothing),
                New Clases.Desarrolladores("Oliver Age 24", "@OliverAge24", Nothing),
                New Clases.Desarrolladores("ONEVISION GAMES", "@ONEVISION_GAMES", Nothing),
                New Clases.Desarrolladores("OrangePixel", "@OrangePixel", Nothing),
                New Clases.Desarrolladores("Osmotic Studios", "@osmoticstudios", Nothing),
                New Clases.Desarrolladores("Outsider Games", "@OutsiderGames", Nothing),
                New Clases.Desarrolladores("Over the Top Games", "@OverTheTopGames", Nothing),
                New Clases.Desarrolladores("Overhype Studios", "@OverhypeStudios", Nothing),
                New Clases.Desarrolladores("Oxymoron Games", "@oxymoron_games", Nothing),
                New Clases.Desarrolladores("Paper Castle Games", "@Underherodevs", Nothing),
                New Clases.Desarrolladores("Paradox Development Studio", "@PDX_Dev_Studio", Nothing),
                New Clases.Desarrolladores("Paradox Interactive", "@PdxInteractive", Nothing),
                New Clases.Desarrolladores("Pathea Games", "@PatheaGames", Nothing),
                New Clases.Desarrolladores("Pathos Interactive", "@PathosInteract", Nothing),
                New Clases.Desarrolladores("Patriot Game", "@GameOfPatriot", Nothing),
                New Clases.Desarrolladores("Payload Studios", "@TerraTechGame", Nothing),
                New Clases.Desarrolladores("Pea Head Games", "@PeaHeadGames", Nothing),
                New Clases.Desarrolladores("Perfect World", "@PlayArcGames", Nothing),
                New Clases.Desarrolladores("Piko Interactive", "@Pikointeractive", Nothing),
                New Clases.Desarrolladores("Pine Studio", "@PineStudioLLC", Nothing),
                New Clases.Desarrolladores("Pinokl Games", "@PinoklGames", Nothing),
                New Clases.Desarrolladores("Pirate Software", "@PirateSoftware", Nothing),
                New Clases.Desarrolladores("PixelCount Studios", "@PixelCountGames", Nothing),
                New Clases.Desarrolladores("Pixeljam", "@pixeljamgames", Nothing),
                New Clases.Desarrolladores("Pixelnest Studio", "@pixelnest", Nothing),
                New Clases.Desarrolladores("PixelTail Games", "@PixelTailGames", Nothing),
                New Clases.Desarrolladores("Playdead", "@Playdead", Nothing),
                New Clases.Desarrolladores("PlayFig", "@PlayFig", Nothing),
                New Clases.Desarrolladores("PLAYISM", "@playismEN", Nothing),
                New Clases.Desarrolladores("Playsaurus", "@ClickerHeroes", Nothing),
                New Clases.Desarrolladores("Plug In Digital", "@plugindigitall", Nothing),
                New Clases.Desarrolladores("Pocketwatch Games", "@PocketwatchG", Nothing),
                New Clases.Desarrolladores("Popcannibal", "@popcannibal", Nothing),
                New Clases.Desarrolladores("Portable Moose", "@PortableMoose", Nothing),
                New Clases.Desarrolladores("Positech Games", "@cliffski", Nothing),
                New Clases.Desarrolladores("Powerhoof", "@Powerhoof", Nothing),
                New Clases.Desarrolladores("Progorion", "@ProgOrion", Nothing),
                New Clases.Desarrolladores("Psyonix", "@PsyonixStudios", Nothing),
                New Clases.Desarrolladores("Puny Human", "@punyhuman", Nothing),
                New Clases.Desarrolladores("Pyrodactyl", "@pyrodactylgames", Nothing),
                New Clases.Desarrolladores("Rain Games", "@rain_games", Nothing),
                New Clases.Desarrolladores("Rake in Grass", "@rakeingrass", Nothing),
                New Clases.Desarrolladores("Rat King Entertainment", "@RatKingsLair", Nothing),
                New Clases.Desarrolladores("Raw Fury Games", "@rawfury", Nothing),
                New Clases.Desarrolladores("Razzart Visual", "@StarlightVega", Nothing),
                New Clases.Desarrolladores("Re-Logic", "@ReLogicGames", Nothing),
                New Clases.Desarrolladores("Rebellion", "@Rebellion", Nothing),
                New Clases.Desarrolladores("Red Barrels", "@TheRedBarrels", Nothing),
                New Clases.Desarrolladores("Red Candle Games", "@redcandlegames", Nothing),
                New Clases.Desarrolladores("Red Hook Studios", "@RedHookStudios", Nothing),
                New Clases.Desarrolladores("Red Thread Games", "@RedThreadGames", Nothing),
                New Clases.Desarrolladores("Redblack Spade", "@RBSpade", Nothing),
                New Clases.Desarrolladores("Reine Works", "@reineworks", Nothing),
                New Clases.Desarrolladores("Reiza Studios", "@ReizaStudios", Nothing),
                New Clases.Desarrolladores("Reptoid Games", "@ReptoidGames", Nothing),
                New Clases.Desarrolladores("Retrific Game Studio", "@Retrific", Nothing),
                New Clases.Desarrolladores("Reverie World Studios", "@MedievalKW", Nothing),
                New Clases.Desarrolladores("Ripstone", "@RipstoneGames", Nothing),
                New Clases.Desarrolladores("Rising Star Games", "@RisingStarGames", Nothing),
                New Clases.Desarrolladores("Rival Games Ltd", "@RivalGamesLtd", Nothing),
                New Clases.Desarrolladores("Robot Entertainment", "@RobotEnt", Nothing),
                New Clases.Desarrolladores("Robot Gentleman", "@robotgentleman", Nothing),
                New Clases.Desarrolladores("Robotality", "@robotality", Nothing),
                New Clases.Desarrolladores("Rogue Snail", "@RelicHuntersU", Nothing),
                New Clases.Desarrolladores("Rolling Crown", "@DemonheartVN", Nothing),
                New Clases.Desarrolladores("roseVeRte", "@rosevertegames", Nothing),
                New Clases.Desarrolladores("Running With Scissors", "@RWSbleeter", Nothing),
                New Clases.Desarrolladores("Sabotage Studio", "@SabotageQc", Nothing),
                New Clases.Desarrolladores("Sad Panda Studios", "@SadPandaStudio", Nothing),
                New Clases.Desarrolladores("SakuraGame", "@SakuraGame_EN", Nothing),
                New Clases.Desarrolladores("Salmi Games", "@SalmiGames", Nothing),
                New Clases.Desarrolladores("Sam Barlow", "@mrsambarlow", Nothing),
                New Clases.Desarrolladores("Samurai Punk", "@SamuraiPunkCo", Nothing),
                New Clases.Desarrolladores("Sauropod Studio", "@SauropodStudio", Nothing),
                New Clases.Desarrolladores("Say Again Studio", "@manfightdragon", Nothing),
                New Clases.Desarrolladores("SCS Software", "@SCSsoftware", Nothing),
                New Clases.Desarrolladores("SEGA", "@SEGA", Nothing),
                New Clases.Desarrolladores("Sekai Project", "@sekaiproject", Nothing),
                New Clases.Desarrolladores("Senscape", "@Senscape", Nothing),
                New Clases.Desarrolladores("Serenity Forge", "@SerenityForge", Nothing),
                New Clases.Desarrolladores("SFB Games", "@SFBTom", Nothing),
                New Clases.Desarrolladores("Shard Real", "@shard_real", Nothing),
                New Clases.Desarrolladores("Shiver Games", "@shivergames", Nothing),
                New Clases.Desarrolladores("shostak.games", "@StasShostak", Nothing),
                New Clases.Desarrolladores("Sigono", "@sigonogames", Nothing),
                New Clases.Desarrolladores("SilentFuture", "@silentfuture_de", Nothing),
                New Clases.Desarrolladores("Silverware Games", "@SilverwareGames", Nothing),
                New Clases.Desarrolladores("Sindiecate Arts", "@SindiecateArts", Nothing),
                New Clases.Desarrolladores("SIXNAILS", "@sixnailsEXIT", Nothing),
                New Clases.Desarrolladores("sixteen tons", "@emergency_game", Nothing),
                New Clases.Desarrolladores("SixtyGig Games", "@RaymondDoerr", Nothing),
                New Clases.Desarrolladores("Ska Studios", "@skastudios", Nothing),
                New Clases.Desarrolladores("Sludj Games", "@SludjGames", Nothing),
                New Clases.Desarrolladores("Sluggerfly", "@SluggerflyDev", Nothing),
                New Clases.Desarrolladores("SmallBigSquare", "@smallbigsquare", Nothing),
                New Clases.Desarrolladores("Smash Game Studios", "@SmashGameStudio", Nothing),
                New Clases.Desarrolladores("SMG Studio", "@smgstudio", Nothing),
                New Clases.Desarrolladores("SnagBox", "@SnagBox_Studio", Nothing),
                New Clases.Desarrolladores("Snail Games USA", "@SnailGamesUSA", Nothing),
                New Clases.Desarrolladores("Snap Finger Click", "@snapfingerclick", Nothing),
                New Clases.Desarrolladores("SnoutUp", "@SnoutUp", Nothing),
                New Clases.Desarrolladores("Snowbird Games", "@SnowbirdGames", Nothing),
                New Clases.Desarrolladores("SOEDESCO", "@SOEDESCO", Nothing),
                New Clases.Desarrolladores("Sol Press", "@SolPressUSA", Nothing),
                New Clases.Desarrolladores("Soldak Entertainment", "@Soldak", Nothing),
                New Clases.Desarrolladores("SomaSim", "@somasim_games", Nothing),
                New Clases.Desarrolladores("Spacewave Software", "@spacewavesoft", Nothing),
                New Clases.Desarrolladores("Sparpweed", "@sparpweed", Nothing),
                New Clases.Desarrolladores("Spearhead Games", "@SpearheadMtl", Nothing),
                New Clases.Desarrolladores("Spiderling Studios", "@spiderlinggames", Nothing),
                New Clases.Desarrolladores("Spike Chunsoft", "@SpikeChunsoft_e", Nothing),
                New Clases.Desarrolladores("Spooky Squid Games", "@spookysquid", Nothing),
                New Clases.Desarrolladores("Square Enix", "@SquareEnix", Nothing),
                New Clases.Desarrolladores("Squid In A Box", "@squidinabox", Nothing),
                New Clases.Desarrolladores("SRRIVERS", "@enigmaprison", Nothing),
                New Clases.Desarrolladores("Stainless Games", "@Stainless_Games", Nothing),
                New Clases.Desarrolladores("Stardock", "@Stardock", Nothing),
                New Clases.Desarrolladores("Steven Colling", "@StevenColling", Nothing),
                New Clases.Desarrolladores("Stromsky", "@Stromsky2", Nothing),
                New Clases.Desarrolladores("Studio Bean", "@OneMrBean", Nothing),
                New Clases.Desarrolladores("Studio Eres", "@rinkuhero", Nothing),
                New Clases.Desarrolladores("Studio Evil", "@STUDIOEVIL", Nothing),
                New Clases.Desarrolladores("Studio MDHR", "@StudioMDHR", Nothing),
                New Clases.Desarrolladores("Studio Roqovan", "@StudioRoqovan", Nothing),
                New Clases.Desarrolladores("Studio Wildcard", "@survivetheark", Nothing),
                New Clases.Desarrolladores("Subset Games", "@subsetgames", Nothing),
                New Clases.Desarrolladores("Sukeban Games", "@SukebanGames", Nothing),
                New Clases.Desarrolladores("Suncrash", "@suncrashstudio", Nothing),
                New Clases.Desarrolladores("Supergiant Games", "@SupergiantGames", Nothing),
                New Clases.Desarrolladores("SureAI", "@SureAITeam", Nothing),
                New Clases.Desarrolladores("Surprise Attack", "@FellowTravellr", Nothing),
                New Clases.Desarrolladores("Suspicious Developments", "@Pentadact", Nothing),
                New Clases.Desarrolladores("SVRVIVE Studios", "@svrviveofficial", Nothing),
                New Clases.Desarrolladores("System Era Softworks", "@astroneergame", Nothing),
                New Clases.Desarrolladores("TaleWorlds Entertainment", "@Mount_and_Blade", Nothing),
                New Clases.Desarrolladores("Tamasenco", "@tamasenco", Nothing),
                New Clases.Desarrolladores("Team17", "@Team17Ltd", Nothing),
                New Clases.Desarrolladores("Team Reptile", "@ReptileGames", Nothing),
                New Clases.Desarrolladores("teamCOIL GAMES", "@teamCOIL", Nothing),
                New Clases.Desarrolladores("Techland", "@TechlandGames", Nothing),
                New Clases.Desarrolladores("Telltale Games", "@telltalegames", Nothing),
                New Clases.Desarrolladores("Tequilabyte Studio", "@StanislavZagniy", Nothing),
                New Clases.Desarrolladores("Tero Lunkka games", "@TerhoTero", Nothing),
                New Clases.Desarrolladores("TERRI VELLMANN", "@terrivellmann", Nothing),
                New Clases.Desarrolladores("The Behemoth", "@thebehemoth", Nothing),
                New Clases.Desarrolladores("The Game Bakers", "@TheGameBakers", Nothing),
                New Clases.Desarrolladores("The Hidden Levels", "@TheHiddenLevels", Nothing),
                New Clases.Desarrolladores("The Neocore Collective", "@NeocoreGames", Nothing),
                New Clases.Desarrolladores("The Sheep's Meow", "@TheSheepsMeow", Nothing),
                New Clases.Desarrolladores("Thing Trunk", "@ThingTrunk", Nothing),
                New Clases.Desarrolladores("Thunder Lotus Games", "@ThunderLotus", Nothing),
                New Clases.Desarrolladores("Throwback Entertainment", "@ThrowbackCorp", Nothing),
                New Clases.Desarrolladores("THQ Nordic", "@THQNordic", Nothing),
                New Clases.Desarrolladores("Timeslip Softworks", "@DaithiMcH", Nothing),
                New Clases.Desarrolladores("Tin Man Games", "@TinManGames", Nothing),
                New Clases.Desarrolladores("tinyBuild", "@tinyBuild", Nothing),
                New Clases.Desarrolladores("TML-Studios", "@TMLStudios", Nothing),
                New Clases.Desarrolladores("Toge Productions", "@togeproductions", Nothing),
                New Clases.Desarrolladores("Tomorrow Corporation", "@TomorrowCorp", Nothing),
                New Clases.Desarrolladores("Top Hat Studios", "@TopHatStudiosEN", Nothing),
                New Clases.Desarrolladores("Total War", "@totalwar", Nothing),
                New Clases.Desarrolladores("Toxic Games", "@ToxicGames", Nothing),
                New Clases.Desarrolladores("Träumendes Mädchen", "@TM_VN", Nothing),
                New Clases.Desarrolladores("Trendy Entertainment", "@TrendyEnt", Nothing),
                New Clases.Desarrolladores("Trese Brothers", "@TreseBrothers", Nothing),
                New Clases.Desarrolladores("Tribute Games", "@TributeGames", Nothing),
                New Clases.Desarrolladores("Tripwire Interactive", "@TripwireInt", Nothing),
                New Clases.Desarrolladores("Triumph Studios", "@TriumphStudios", Nothing),
                New Clases.Desarrolladores("Triverske", "@Triverske", Nothing),
                New Clases.Desarrolladores("Turbo Button", "@TurboButtonInc", Nothing),
                New Clases.Desarrolladores("U Game Me", "@ugameme", Nothing),
                New Clases.Desarrolladores("Ubisoft", "@Ubisoft", Nothing),
                New Clases.Desarrolladores("unbeGames", "@unbeGames", Nothing),
                New Clases.Desarrolladores("Unbound Creations", "@UnboundCreation", Nothing),
                New Clases.Desarrolladores("UppercutGames", "@UppercutGames", Nothing),
                New Clases.Desarrolladores("Upfall Studios", "@UpfallStudios", Nothing),
                New Clases.Desarrolladores("U-PLAY Online", "@uplayonline", Nothing),
                New Clases.Desarrolladores("Valhalla Cats", "@valhallacats", Nothing),
                New Clases.Desarrolladores("VaragtP", "@VaragtP", Nothing),
                New Clases.Desarrolladores("Variable State", "@VariableState", Nothing),
                New Clases.Desarrolladores("VDOGMS", "@CallysCaves", Nothing),
                New Clases.Desarrolladores("Versus Evil", "@vs_evil", Nothing),
                New Clases.Desarrolladores("Vertigo Gaming", "@hubigans", Nothing),
                New Clases.Desarrolladores("Vile Monarch", "@VileMonarch", Nothing),
                New Clases.Desarrolladores("Villa Gorilla", "@YokuGame", Nothing),
                New Clases.Desarrolladores("VisualArts/Key", "@VisualArtsUSA", Nothing),
                New Clases.Desarrolladores("Vladimir Maslov", "@vladimir_maslov", Nothing),
                New Clases.Desarrolladores("Vlambeer", "@Vlambeer", Nothing),
                New Clases.Desarrolladores("VooFoo Studios", "@VooFoo", Nothing),
                New Clases.Desarrolladores("Wadjet Eye Games", "@WadjetEyeGames", Nothing),
                New Clases.Desarrolladores("Wales Interactive", "@WalesInter", Nothing),
                New Clases.Desarrolladores("Wargaming World Limited", "@wargaming_net", Nothing),
                New Clases.Desarrolladores("Warhorse Studios", "@WarhorseStudios", Nothing),
                New Clases.Desarrolladores("Warner Bros", "@wbgames", "Assets\Publishers\warnerbros.png"),
                New Clases.Desarrolladores("Wastelands Interactive", "@WstlInteractive", Nothing),
                New Clases.Desarrolladores("WayForward", "@WayForward", Nothing),
                New Clases.Desarrolladores("Wayward Prophet", "@wayward_prophet", Nothing),
                New Clases.Desarrolladores("Weather Factory", "@factoryweather", Nothing),
                New Clases.Desarrolladores("WeirdBeard", "@WeirdBeardGames", Nothing),
                New Clases.Desarrolladores("Wild Factor", "@WildFactorGames", Nothing),
                New Clases.Desarrolladores("Wild Rooster", "@WildRooster", Nothing),
                New Clases.Desarrolladores("Windybeard", "@WindybeardGames", Nothing),
                New Clases.Desarrolladores("Winter Wolves Games", "@pcmacgames", Nothing),
                New Clases.Desarrolladores("Wired Productions", "@WiredP", Nothing),
                New Clases.Desarrolladores("Wolcen Studio", "@WolcenGame", Nothing),
                New Clases.Desarrolladores("Wolfire Games", "@Wolfire", Nothing),
                New Clases.Desarrolladores("Wonderful Lasers", "@lasersinc", Nothing),
                New Clases.Desarrolladores("XREAL Games", "@XREALGames", Nothing),
                New Clases.Desarrolladores("XSEED Games", "@XSEEDGames", Nothing),
                New Clases.Desarrolladores("Yacht Club Games", "@YachtClubGames", Nothing),
                New Clases.Desarrolladores("Yai Gameworks", "@YaiGameworks", Nothing),
                New Clases.Desarrolladores("Yangyang Mobile", "@yangyangmobile", Nothing),
                New Clases.Desarrolladores("Young Horses", "@YoungHorses", Nothing),
                New Clases.Desarrolladores("Your Daily Fill", "@EpicSkaterGame", Nothing),
                New Clases.Desarrolladores("Ysbryd Games", "@YsbrydGames", Nothing),
                New Clases.Desarrolladores("Zachtronics", "@zachtronics", Nothing),
                New Clases.Desarrolladores("Zeiva Inc", "@zeivainc", Nothing),
                New Clases.Desarrolladores("Zen Studios", "@zen_studios", Nothing),
                New Clases.Desarrolladores("Zero Gravity Games", "@playhellion", Nothing),
                New Clases.Desarrolladores("Zoink Games", "@ZoinkGames", Nothing),
                New Clases.Desarrolladores("Zombie Panic! Team", "@zombiepanic_dev", Nothing),
                New Clases.Desarrolladores("Zordix", "@ZordixGames", Nothing)
            }

            Return lista
        End Function

        Public Function LimpiarPublisher(publisher As String)

            Dim listaCaracteres As New List(Of String) From {"Games", "Entertainment", "Productions", "Studios", "Ltd",
                "S.L.", "LLC", "GAMES", "Inc", "Studio", "The", "LTD", "Software", "Game", "GmbH", "Softworks", "Digital",
                "Interactive", "Developments",
                " ", "•", ">", "<", "¿", "?", "!", "¡", ":", ".", "_", "–", "-", ";", ",", "™", "®", "'", "’", "´",
                "`", "(", ")", "/", "\", "|", "&", "#", "=", ChrW(34), "@", "^", "[", "]", "ª", "«"}

            For Each item In listaCaracteres
                publisher = publisher.Replace(item, Nothing)
            Next

            publisher = publisher.ToLower
            publisher = publisher.Trim

            Return publisher
        End Function

    End Module
End Namespace

