Namespace pepeizq.Editor.pepeizqdeals
    Module Desarrolladores

        Public Sub GenerarDatos()

            Dim listaPublishers As List(Of Clases.Desarrolladores) = CargarLista()

            Dim frame As Frame = Window.Current.Content
            Dim pagina As Page = frame.Content

            Dim cb As ComboBox = pagina.FindName("cbEditorTitulopepeizqdealsPublishers")
            cb.Items.Clear()

            cb.Items.Add("--")

            If listaPublishers.Count > 0 Then
                For Each publisher In listaPublishers
                    Dim tb As New TextBlock With {
                        .Text = publisher.Publisher,
                        .Tag = publisher.Twitter
                    }

                    cb.Items.Add(tb)
                Next
            End If

            cb.SelectedIndex = 0

            AddHandler cb.SelectionChanged, AddressOf CambiarTitulo

        End Sub

        Private Sub CambiarTitulo(sender As Object, e As SelectionChangedEventArgs)

            Dim frame As Frame = Window.Current.Content
            Dim pagina As Page = frame.Content

            Dim cb As ComboBox = sender

            Dim tbTitulo As TextBox = pagina.FindName("tbEditorTitulopepeizqdeals")

            If Not cb.SelectedIndex = 0 Then
                If Not tbTitulo.Text = Nothing Then
                    If tbTitulo.Text.Contains("Sale") Then
                        Dim publisher As TextBlock = cb.SelectedItem

                        If Not publisher Is Nothing Then
                            tbTitulo.Text = publisher.Text + " " + tbTitulo.Text
                        End If
                    End If
                End If
            End If

        End Sub

        Private Function CargarLista()

            Dim lista As New List(Of Clases.Desarrolladores) From {
                New Clases.Desarrolladores("10tons", "@10tonsLtd"),
                New Clases.Desarrolladores("11 bit studios", "@11bitstudios"),
                New Clases.Desarrolladores("1C Company", "@1C_Company"),
                New Clases.Desarrolladores("2K", "@2K"),
                New Clases.Desarrolladores("2 Zombie Games", "@2zombiegames"),
                New Clases.Desarrolladores("34BigThings", "@34bigthings"),
                New Clases.Desarrolladores("3D Avenue", "@3D_Avenue"),
                New Clases.Desarrolladores("3DClouds.it", "@3DClouds"),
                New Clases.Desarrolladores("505 Games", "@505_Games"),
                New Clases.Desarrolladores("Abbey Games", "@AbbeyGamesNL"),
                New Clases.Desarrolladores("Abylight Studios", "@abylight"),
                New Clases.Desarrolladores("ACE Team", "@theACETeam"),
                New Clases.Desarrolladores("Adliberum", "@liamtwose"),
                New Clases.Desarrolladores("Adult Swim", "@adultswimgames"),
                New Clases.Desarrolladores("Aerosoft", "@AerosoftGmbH"),
                New Clases.Desarrolladores("Akupara Games", "@akuparagames"),
                New Clases.Desarrolladores("Aksys Games", "@aksysgames"),
                New Clases.Desarrolladores("ALICE IN DISSONANCE", "@projectwritten"),
                New Clases.Desarrolladores("Alientrap", "@AlientrapGames"),
                New Clases.Desarrolladores("Amanita Design", "@Amanita_Design"),
                New Clases.Desarrolladores("Ammobox Studios", "@ammoboxstudios"),
                New Clases.Desarrolladores("Amplitude Studios", "@Amplitude"),
                New Clases.Desarrolladores("Analgesic Productions", "@analgesicprod"),
                New Clases.Desarrolladores("Ankama", "@AnkamaGames"),
                New Clases.Desarrolladores("Annapurna Interactive", "@A_i"),
                New Clases.Desarrolladores("Another Indie", "@AnotherIndieS"),
                New Clases.Desarrolladores("Applava", "@Applava"),
                New Clases.Desarrolladores("Auroch Digital", "@AurochDigital"),
                New Clases.Desarrolladores("Autarca", "@AutarcaDev"),
                New Clases.Desarrolladores("Arc System Works", "@ArcSystemWorksU"),
                New Clases.Desarrolladores("Artifex Mundi", "@ArtifexMundi"),
                New Clases.Desarrolladores("Aspyr", "@AspyrMedia"),
                New Clases.Desarrolladores("astragon Entertainment", "@astragon_GmbH"),
                New Clases.Desarrolladores("Atelier 801", "@Atelier801"),
                New Clases.Desarrolladores("Atomic Fabrik", "@atomicfabrik"),
                New Clases.Desarrolladores("Awesome Games Studio", "@AwesomeGamesStd"),
                New Clases.Desarrolladores("Bandai Namco", "@BandaiNamcoEU"),
                New Clases.Desarrolladores("BattleGoat Studios", "@BattleGoat"),
                New Clases.Desarrolladores("Beamdog", "@BeamdogInc"),
                New Clases.Desarrolladores("BeautiFun Games", "@BeautiFunGames"),
                New Clases.Desarrolladores("Bedtime Digital Games", "@BedtimeDG"),
                New Clases.Desarrolladores("Bethesda", "@bethesda"),
                New Clases.Desarrolladores("Betadwarf", "@BetaDwarf"),
                New Clases.Desarrolladores("Big Robot Ltd", "@BigRobotLtd"),
                New Clases.Desarrolladores("Big Evil Corp", "@Big_Evil_Corp"),
                New Clases.Desarrolladores("Bigben Games", "@Bigben_games"),
                New Clases.Desarrolladores("Bigosaur", "@Bigosaur"),
                New Clases.Desarrolladores("Bitbox", "@LifeisFeudal"),
                New Clases.Desarrolladores("Black Icicles", "@BlackIceTheGame"),
                New Clases.Desarrolladores("Black Forest Games", "@BlackForestTeam"),
                New Clases.Desarrolladores("BlackEye Games", "@GloriaVictisMMO"),
                New Clases.Desarrolladores("Blacklight Interactive", "@BlackLightInt"),
                New Clases.Desarrolladores("BlackMill Games", "@BlackMillGame"),
                New Clases.Desarrolladores("Blazing Griffin", "@BlazingGriffin"),
                New Clases.Desarrolladores("Blendo Games", "@BlendoGames"),
                New Clases.Desarrolladores("Blue Isle Studios", "@BlueIsleStudio"),
                New Clases.Desarrolladores("Bohemia Interactive", "@bohemiainteract"),
                New Clases.Desarrolladores("Brace Yourself Games", "@BYG_Vancouver"),
                New Clases.Desarrolladores("Brilliant Game Studios", "@BrilliantGames"),
                New Clases.Desarrolladores("BT Studios", "@btstudiosgames"),
                New Clases.Desarrolladores("Buka Entertainment", "@Buka_Ent_Games"),
                New Clases.Desarrolladores("BURA", "@lgdays"),
                New Clases.Desarrolladores("Butterscotch", "@BScotchShenani"),
                New Clases.Desarrolladores("Capcom", "@CapcomUSA_"),
                New Clases.Desarrolladores("Capybara Games", "@CAPYGAMES"),
                New Clases.Desarrolladores("Carbon Games", "@CarbonGames"),
                New Clases.Desarrolladores("Cat Nigiri", "@CatNigiri"),
                New Clases.Desarrolladores("CCP Games", "@CCPGames"),
                New Clases.Desarrolladores("CCCP-games", "@LeCCCP"),
                New Clases.Desarrolladores("CD PROJEKT RED", "@CDPROJEKTRED"),
                New Clases.Desarrolladores("Cellar Door Games", "@CellarDoorGames"),
                New Clases.Desarrolladores("Chasing Carrots", "@Chasing_Carrots"),
                New Clases.Desarrolladores("Choice of Games", "@choiceofgames"),
                New Clases.Desarrolladores("Chucklefish", "@ChucklefishLTDs"),
                New Clases.Desarrolladores("CI Games", "@CIGamesOfficial"),
                New Clases.Desarrolladores("CINEMAX GAMES", "@CINEMAXGAMES"),
                New Clases.Desarrolladores("Clapfoot", "@foxholegame"),
                New Clases.Desarrolladores("Clever Endeavour", "@ClevEndeavGames"),
                New Clases.Desarrolladores("Clickteam", "@Clickteam"),
                New Clases.Desarrolladores("Cloudhead Games", "@CloudheadGames"),
                New Clases.Desarrolladores("CoaguCo Industries", "@CoaguCo"),
                New Clases.Desarrolladores("Cockroach Inc", "@theDreamGame"),
                New Clases.Desarrolladores("Codemasters", "@Codemasters"),
                New Clases.Desarrolladores("Codename Entertainment", "@CodenameEnt"),
                New Clases.Desarrolladores("ConcernedApe", "@ConcernedApe"),
                New Clases.Desarrolladores("Copychaser Games", "@bengelinas"),
                New Clases.Desarrolladores("Cosmo D Studios", "@cosmoddd"),
                New Clases.Desarrolladores("COWCAT Games", "@COWCATGames"),
                New Clases.Desarrolladores("Crate Entertainment", "@GrimDawn"),
                New Clases.Desarrolladores("Crazy Monkey Studios", "@CrazyMonkeyStu"),
                New Clases.Desarrolladores("Croteam", "@Croteam"),
                New Clases.Desarrolladores("Crows Crows Crows", "@crowsx3"),
                New Clases.Desarrolladores("Crytivo", "@Crytivo"),
                New Clases.Desarrolladores("Curve Digital", "@CurveDigital"),
                New Clases.Desarrolladores("Cyan Worlds Inc", "@cyanworlds"),
                New Clases.Desarrolladores("Cyanide Studio", "@CyanideStudio"),
                New Clases.Desarrolladores("D-Pad Studio", "@DPadStudio"),
                New Clases.Desarrolladores("D3 PUBLISHER", "@D3_PUBLISHER"),
                New Clases.Desarrolladores("Daedalic", "@daedalic"),
                New Clases.Desarrolladores("Daniel Mullins Games", "@DMullinsGames"),
                New Clases.Desarrolladores("David Stark", "@zarkonnen_com"),
                New Clases.Desarrolladores("Daylight-Studios", "@holypotatogame"),
                New Clases.Desarrolladores("Deadpan Games", "@onegamewill"),
                New Clases.Desarrolladores("DECK13 Interactive", "@Deck13_de"),
                New Clases.Desarrolladores("Deep Silver", "@deepsilver"),
                New Clases.Desarrolladores("Degica", "@DegicaGames"),
                New Clases.Desarrolladores("Destructive Creations", "@DestCreat_Team"),
                New Clases.Desarrolladores("Devilish Games", "@devilishgames"),
                New Clases.Desarrolladores("Devolver Digital", "@devolverdigital"),
                New Clases.Desarrolladores("Digital Cybercherries", "@DCybercherries"),
                New Clases.Desarrolladores("Digital Extremes", "@PlayWarframe"),
                New Clases.Desarrolladores("Digitalmindsoft", "@digitalmindsoft"),
                New Clases.Desarrolladores("Dinosaur Polo Club", "@dinopoloclub"),
                New Clases.Desarrolladores("DireWolfDigital", "@direwolfdigital"),
                New Clases.Desarrolladores("DLsite", "@DLsite"),
                New Clases.Desarrolladores("Dodge Roll", "@DodgeRollGames"),
                New Clases.Desarrolladores("Dotemu", "@Dotemu"),
                New Clases.Desarrolladores("Double Eleven LTD", "@DoubleElevenLtd"),
                New Clases.Desarrolladores("Double Fine", "@DoubleFine"),
                New Clases.Desarrolladores("Double Stallion Games", "@dblstallion"),
                New Clases.Desarrolladores("DoubleBear Productions", "@DoubleBearGames"),
                New Clases.Desarrolladores("DoubleDutch Games", "@dd_games"),
                New Clases.Desarrolladores("Draknek", "@Draknek"),
                New Clases.Desarrolladores("DrinkBox Studios", "@DrinkBoxStudios"),
                New Clases.Desarrolladores("Drool LLC", "@ThumperGame"),
                New Clases.Desarrolladores("DRUNKEN APES GAMES", "@DrunkenApes"),
                New Clases.Desarrolladores("DYA Games", "@DYAGames"),
                New Clases.Desarrolladores("Eat Create Sleep", "@EatCreateSleep"),
                New Clases.Desarrolladores("ebi-hime", "@ebihimes"),
                New Clases.Desarrolladores("Egosoft", "@EGOSOFT"),
                New Clases.Desarrolladores("Eidos Montréal", "@EidosMontreal"),
                New Clases.Desarrolladores("Ellada Games", "@ElladaGames"),
                New Clases.Desarrolladores("Endless Loop Studios", "@EndlessLoopStd"),
                New Clases.Desarrolladores("EnsenaSoft", "@ensenasoft"),
                New Clases.Desarrolladores("Eugen Systems", "@EugenSystems"),
                New Clases.Desarrolladores("Ertal Games", "@ertal77"),
                New Clases.Desarrolladores("EvilCoGames", "@EvilCoGames"),
                New Clases.Desarrolladores("Excalibur Games", "@Excalpublishing"),
                New Clases.Desarrolladores("Exor Studios", "@EXORStudios"),
                New Clases.Desarrolladores("Fabraz", "@Fabrazz"),
                New Clases.Desarrolladores("Failbetter Games", "@failbettergames"),
                New Clases.Desarrolladores("Fantasy Grounds", "@FantasyGrounds2"),
                New Clases.Desarrolladores("Fatshark", "@fatsharkgames"),
                New Clases.Desarrolladores("Fellow Traveller", "@FellowTravellr"),
                New Clases.Desarrolladores("Finji", "@FinjiCo"),
                New Clases.Desarrolladores("Firaxis Games", "@FiraxisGames"),
                New Clases.Desarrolladores("Firefly Studios", "@fireflyworlds"),
                New Clases.Desarrolladores("Fireproof Games", "@Fireproof_Games"),
                New Clases.Desarrolladores("Fishing Cactus", "@FishingCactus"),
                New Clases.Desarrolladores("Flashbulb", "@flashbulbgames"),
                New Clases.Desarrolladores("Focus Home", "@FocusHome"),
                New Clases.Desarrolladores("Forgotten Empires", "@ForgottenEmp"),
                New Clases.Desarrolladores("Freebird Games", "@Reives_Freebird"),
                New Clases.Desarrolladores("Freejam", "@Freejamgames"),
                New Clases.Desarrolladores("FreezeNova Games", "@FreezeNova"),
                New Clases.Desarrolladores("Frictional Games", "@frictionalgames"),
                New Clases.Desarrolladores("Frogwares", "@Frogwares"),
                New Clases.Desarrolladores("Frontwing USA", "@FrontwingInt"),
                New Clases.Desarrolladores("Frozenbyte", "@Frozenbyte"),
                New Clases.Desarrolladores("Fruitbat Factory", "@FruitbatFactory"),
                New Clases.Desarrolladores("Fun Bits Interactive", "@SquidsFromSpace"),
                New Clases.Desarrolladores("Funcom", "@funcom"),
                New Clases.Desarrolladores("Funktronic Labs", "@funktroniclabs"),
                New Clases.Desarrolladores("Gambrinous", "@gambrinous"),
                New Clases.Desarrolladores("Gameconnect", "@gameconnectnet"),
                New Clases.Desarrolladores("Gamepires", "@Gamepires"),
                New Clases.Desarrolladores("Gamera Interactive", "@gameragamesint"),
                New Clases.Desarrolladores("Games Operators", "@GamesOperators"),
                New Clases.Desarrolladores("Gato Salvaje S.L.", "@GatoSalvajeDEV"),
                New Clases.Desarrolladores("GFX47 Games", "@GFX47"),
                New Clases.Desarrolladores("Ghost Ship Games", "@JoinDeepRock"),
                New Clases.Desarrolladores("Glaiel Games", "@TylerGlaiel"),
                New Clases.Desarrolladores("GoblinzStudio", "@studio_goblinz"),
                New Clases.Desarrolladores("Green Man Gaming", "@gmg_publishing"),
                New Clases.Desarrolladores("Greenheart Games", "@GreenheartGames"),
                New Clases.Desarrolladores("Grey Alien Games", "@GreyAlien"),
                New Clases.Desarrolladores("Grip Digital", "@Grip_Digital"),
                New Clases.Desarrolladores("Groupees", "@groupees1"),
                New Clases.Desarrolladores("HakJak", "@HakJakGames"),
                New Clases.Desarrolladores("Hammer&Ravens", "@Ham_Rav"),
                New Clases.Desarrolladores("Hanako Games", "@HanakoGames"),
                New Clases.Desarrolladores("HandyGames", "@handy_games"),
                New Clases.Desarrolladores("Headup Games", "@HeadupGames"),
                New Clases.Desarrolladores("Heart Shaped Games", "@heartshapedgame"),
                New Clases.Desarrolladores("Hemisphere Games", "@HemisphereGames"),
                New Clases.Desarrolladores("HeR Interactive", "@HerInteractive"),
                New Clases.Desarrolladores("Hidden Path Entertainment", "@HiddenPathEnt"),
                New Clases.Desarrolladores("HIKARI FIELD", "@hikari_field"),
                New Clases.Desarrolladores("Hinterland Studio", "@HinterlandGames"),
                New Clases.Desarrolladores("HOF Studios", "@depthextinction"),
                New Clases.Desarrolladores("Hoplon Infotainment", "@HMM_Hoplon_EN"),
                New Clases.Desarrolladores("Humble Bundle", "@humble"),
                New Clases.Desarrolladores("HypeTrain Digital", "@HypeTrainD"),
                New Clases.Desarrolladores("Ice-Pick Lodge", "@IcePickLodge"),
                New Clases.Desarrolladores("Iceberg", "@Iceberg_Int"),
                New Clases.Desarrolladores("IDALGAME", "@IDALGAME"),
                New Clases.Desarrolladores("Idea Factory", "@IdeaFactoryIntl"),
                New Clases.Desarrolladores("Image & Form", "@ImageForm"),
                New Clases.Desarrolladores("Imperium42 Game Studio", "@TheThroneOfLies"),
                New Clases.Desarrolladores("INDIECODE GAMES", "@INDIECODE_GAMES"),
                New Clases.Desarrolladores("IndieGala", "@IndieGala"),
                New Clases.Desarrolladores("inkle", "@inkleStudios"),
                New Clases.Desarrolladores("Introversion Software", "@IVSoftware"),
                New Clases.Desarrolladores("InvertMouse", "@InvertMouse"),
                New Clases.Desarrolladores("ION LANDS", "@ionlands"),
                New Clases.Desarrolladores("Jackbox Games", "@jackboxgames"),
                New Clases.Desarrolladores("JAST", "@jastusa"),
                New Clases.Desarrolladores("JForce Games", "@JForceGames"),
                New Clases.Desarrolladores("JIW-Games", "@JIWGames"),
                New Clases.Desarrolladores("Jolly Crouton Media", "@jollycrouton"),
                New Clases.Desarrolladores("Jundroo", "@JundrooGames"),
                New Clases.Desarrolladores("Kagura Games", "@KaguraGaming"),
                New Clases.Desarrolladores("Kaleido Games", "@KaleidoGames"),
                New Clases.Desarrolladores("Kalypso", "@kalypsomediausa"),
                New Clases.Desarrolladores("KillHouse Games", "@inthekillhouse"),
                New Clases.Desarrolladores("Kitfox Games", "@KitfoxGames"),
                New Clases.Desarrolladores("Klei", "@klei"),
                New Clases.Desarrolladores("Knuckle Cracker", "@knucracker"),
                New Clases.Desarrolladores("Konami", "@Konami"),
                New Clases.Desarrolladores("Konstructors Entertainment", "@konstructors"),
                New Clases.Desarrolladores("LAME Dimension", "@ChairGTables"),
                New Clases.Desarrolladores("Larian Studios", "@larianstudios"),
                New Clases.Desarrolladores("League of Geeks", "@ArmelloGame"),
                New Clases.Desarrolladores("Lo-Fi Games", "@KenshiOfficial"),
                New Clases.Desarrolladores("Loiste Interactive", "@LoisteInteract"),
                New Clases.Desarrolladores("Loren Lemcke", "@LorenLemcke"),
                New Clases.Desarrolladores("Lince Works", "@LinceWorks"),
                New Clases.Desarrolladores("Lion Shield Studios", "@kingdomscastles"),
                New Clases.Desarrolladores("Lucid Games Ltd", "@LucidGamesLtd"),
                New Clases.Desarrolladores("Lupiesoft", "@Lupiesoft"),
                New Clases.Desarrolladores("M2H", "@M2Hgames"),
                New Clases.Desarrolladores("Mandragora Studio", "@MandragoraTeam"),
                New Clases.Desarrolladores("MangaGamer", "@MangaGamer"),
                New Clases.Desarrolladores("Marcelo Barbosa", "@tchecoforevis"),
                New Clases.Desarrolladores("Marmalade Game Studio", "@MarmaladeGames"),
                New Clases.Desarrolladores("Marvelous Europe", "@marvelous_games"),
                New Clases.Desarrolladores("Massive Damage", "@Massive_Damage"),
                New Clases.Desarrolladores("Mechanical Boss", "@MechanicalBoss"),
                New Clases.Desarrolladores("Meridian4", "@Meridian4"),
                New Clases.Desarrolladores("messhof", "@messhof"),
                New Clases.Desarrolladores("Mi-Clos Studio", "@Mi_Clos"),
                New Clases.Desarrolladores("Micropsia Games", "@micropsiagames"),
                New Clases.Desarrolladores("Midgar Studio", "@MidgarStudio"),
                New Clases.Desarrolladores("Might & Delight", "@MightAndDelight"),
                New Clases.Desarrolladores("Milkstone Studios", "@milkstone"),
                New Clases.Desarrolladores("Mimimi", "@MimimiProd"),
                New Clases.Desarrolladores("Mode 7 Games", "@mode7games"),
                New Clases.Desarrolladores("Modern Storyteller", "@ModnStoryteller"),
                New Clases.Desarrolladores("Modii Games", "@modiigames"),
                New Clases.Desarrolladores("Mohawk Games", "@mohawkgames"),
                New Clases.Desarrolladores("Monolith Productions", "@MonolithDev"),
                New Clases.Desarrolladores("Monomi Park", "@monomipark"),
                New Clases.Desarrolladores("Monstrum Games", "@monstersden"),
                New Clases.Desarrolladores("Motion Twin", "@motiontwin"),
                New Clases.Desarrolladores("Nadeo", "@Maniaplanet"),
                New Clases.Desarrolladores("narayana games", "@jashan"),
                New Clases.Desarrolladores("Ndemic Creations", "@NdemicCreations"),
                New Clases.Desarrolladores("New Blood Interactive", "@TheNewBloods"),
                New Clases.Desarrolladores("Nezon Production", "@NezonProduction"),
                New Clases.Desarrolladores("Night Dive Studios", "@NightdiveStudio"),
                New Clases.Desarrolladores("Ninja Theory", "@NinjaTheory"),
                New Clases.Desarrolladores("NIS America", "@NISAmerica"),
                New Clases.Desarrolladores("No More Robots", "@nomorerobotshq"),
                New Clases.Desarrolladores("No Goblin", "@no_goblin"),
                New Clases.Desarrolladores("Nomad Games", "@Nomadgames"),
                New Clases.Desarrolladores("Nonadecimal Creative", "@Nonadecimal"),
                New Clases.Desarrolladores("Ntroy", "@PDO2online"),
                New Clases.Desarrolladores("Nyamyam", "@nyamyamgames"),
                New Clases.Desarrolladores("Nyu Media", "@nyumedia"),
                New Clases.Desarrolladores("Obsidian Entertainment", "@obsidian"),
                New Clases.Desarrolladores("Oddworld Inhabitants", "@OddworldInc"),
                New Clases.Desarrolladores("OhNooStudio", "@OhNooStudio"),
                New Clases.Desarrolladores("Oliver Age 24", "@OliverAge24"),
                New Clases.Desarrolladores("ONEVISION GAMES", "@ONEVISION_GAMES"),
                New Clases.Desarrolladores("OrangePixel", "@OrangePixel"),
                New Clases.Desarrolladores("Over the Top Games", "@OverTheTopGames"),
                New Clases.Desarrolladores("Overhype Studios", "@OverhypeStudios"),
                New Clases.Desarrolladores("Oxymoron Games", "@oxymoron_games"),
                New Clases.Desarrolladores("Paper Castle Games", "@Underherodevs"),
                New Clases.Desarrolladores("Paradox Development Studio", "@PDX_Dev_Studio"),
                New Clases.Desarrolladores("Paradox Interactive", "@PdxInteractive"),
                New Clases.Desarrolladores("Pathea Games", "@PatheaGames"),
                New Clases.Desarrolladores("Pathos Interactive", "@PathosInteract"),
                New Clases.Desarrolladores("Patriot Game", "@GameOfPatriot"),
                New Clases.Desarrolladores("Payload Studios", "@TerraTechGame"),
                New Clases.Desarrolladores("Perfect World", "@PlayArcGames"),
                New Clases.Desarrolladores("Piko Interactive", "@Pikointeractive"),
                New Clases.Desarrolladores("Pinokl Games", "@PinoklGames"),
                New Clases.Desarrolladores("Pirate Software", "@PirateSoftware"),
                New Clases.Desarrolladores("PixelCount Studios", "@PixelCountGames"),
                New Clases.Desarrolladores("Pixeljam", "@pixeljamgames"),
                New Clases.Desarrolladores("Pixelnest Studio", "@pixelnest"),
                New Clases.Desarrolladores("PixelTail Games", "@PixelTailGames"),
                New Clases.Desarrolladores("PlayFig", "@PlayFig"),
                New Clases.Desarrolladores("PLAYISM", "@playismEN"),
                New Clases.Desarrolladores("Pocketwatch Games", "@PocketwatchG"),
                New Clases.Desarrolladores("Portable Moose", "@PortableMoose"),
                New Clases.Desarrolladores("Positech Games", "@cliffski"),
                New Clases.Desarrolladores("Powerhoof", "@Powerhoof"),
                New Clases.Desarrolladores("Psyonix", "@PsyonixStudios"),
                New Clases.Desarrolladores("Rain Games", "@rain_games"),
                New Clases.Desarrolladores("Rat King Entertainment", "@RatKingsLair"),
                New Clases.Desarrolladores("Raw Fury Games", "@rawfury"),
                New Clases.Desarrolladores("Razzart Visual", "@StarlightVega"),
                New Clases.Desarrolladores("Re-Logic", "@ReLogicGames"),
                New Clases.Desarrolladores("Rebellion", "@Rebellion"),
                New Clases.Desarrolladores("Red Barrels", "@TheRedBarrels"),
                New Clases.Desarrolladores("Red Candle Games", "@redcandlegames"),
                New Clases.Desarrolladores("Red Hook Studios", "@RedHookStudios"),
                New Clases.Desarrolladores("Red Thread Games", "@RedThreadGames"),
                New Clases.Desarrolladores("Redblack Spade", "@RBSpade"),
                New Clases.Desarrolladores("Reiza Studios", "@ReizaStudios"),
                New Clases.Desarrolladores("Reverie World Studios", "@MedievalKW"),
                New Clases.Desarrolladores("Ripstone", "@RipstoneGames"),
                New Clases.Desarrolladores("Rising Star Games", "@RisingStarGames"),
                New Clases.Desarrolladores("Robot Entertainment", "@RobotEnt"),
                New Clases.Desarrolladores("Robot Gentleman", "@robotgentleman"),
                New Clases.Desarrolladores("Robotality", "@robotality"),
                New Clases.Desarrolladores("Rogue Snail", "@RelicHuntersU"),
                New Clases.Desarrolladores("Running With Scissors", "@RWSbleeter"),
                New Clases.Desarrolladores("Sabotage Studio", "@SabotageQc"),
                New Clases.Desarrolladores("Sad Panda Studios", "@SadPandaStudio"),
                New Clases.Desarrolladores("SakuraGame", "@SakuraGame_EN"),
                New Clases.Desarrolladores("Salmi Games", "@SalmiGames"),
                New Clases.Desarrolladores("Sam Barlow", "@mrsambarlow"),
                New Clases.Desarrolladores("Samurai Punk", "@SamuraiPunkCo"),
                New Clases.Desarrolladores("Sauropod Studio", "@SauropodStudio"),
                New Clases.Desarrolladores("Say Again Studio", "@manfightdragon"),
                New Clases.Desarrolladores("SCS Software", "@SCSsoftware"),
                New Clases.Desarrolladores("SEGA", "@SEGA"),
                New Clases.Desarrolladores("Sekai Project", "@sekaiproject"),
                New Clases.Desarrolladores("Senscape", "@Senscape"),
                New Clases.Desarrolladores("Serenity Forge", "@SerenityForge"),
                New Clases.Desarrolladores("SFB Games", "@SFBTom"),
                New Clases.Desarrolladores("Shiver Games", "@shivergames"),
                New Clases.Desarrolladores("Sigono", "@sigonogames"),
                New Clases.Desarrolladores("SilentFuture", "@silentfuture_de"),
                New Clases.Desarrolladores("sixteen tons", "@emergency_game"),
                New Clases.Desarrolladores("SixtyGig Games", "@RaymondDoerr"),
                New Clases.Desarrolladores("Ska Studios", "@skastudios"),
                New Clases.Desarrolladores("Sludj Games", "@SludjGames"),
                New Clases.Desarrolladores("Sluggerfly", "@SluggerflyDev"),
                New Clases.Desarrolladores("SmallBigSquare", "@smallbigsquare"),
                New Clases.Desarrolladores("SMG Studio", "@smgstudio"),
                New Clases.Desarrolladores("Snail Games USA", "@SnailGamesUSA"),
                New Clases.Desarrolladores("Snap Finger Click", "@snapfingerclick"),
                New Clases.Desarrolladores("SnoutUp", "@SnoutUp"),
                New Clases.Desarrolladores("SOEDESCO", "@SOEDESCO"),
                New Clases.Desarrolladores("Sol Press", "@SolPressUSA"),
                New Clases.Desarrolladores("Spearhead Games", "@SpearheadMtl"),
                New Clases.Desarrolladores("Spike Chunsoft", "@SpikeChunsoft_e"),
                New Clases.Desarrolladores("Spooky Squid Games", "@spookysquid"),
                New Clases.Desarrolladores("Square Enix", "@SquareEnix"),
                New Clases.Desarrolladores("SRRIVERS", "@enigmaprison"),
                New Clases.Desarrolladores("Stainless Games", "@Stainless_Games"),
                New Clases.Desarrolladores("Stardock", "@Stardock"),
                New Clases.Desarrolladores("Studio Bean", "@OneMrBean"),
                New Clases.Desarrolladores("Studio Eres", "@rinkuhero"),
                New Clases.Desarrolladores("Studio Evil", "@STUDIOEVIL"),
                New Clases.Desarrolladores("Studio MDHR", "@StudioMDHR"),
                New Clases.Desarrolladores("Studio Roqovan", "@StudioRoqovan"),
                New Clases.Desarrolladores("Studio Wildcard", "@survivetheark"),
                New Clases.Desarrolladores("Subset Games", "@subsetgames"),
                New Clases.Desarrolladores("Sukeban Games", "@SukebanGames"),
                New Clases.Desarrolladores("Supergiant Games", "@SupergiantGames"),
                New Clases.Desarrolladores("SureAI", "@SureAITeam"),
                New Clases.Desarrolladores("Surprise Attack", "@FellowTravellr"),
                New Clases.Desarrolladores("Suspicious Developments", "@Pentadact"),
                New Clases.Desarrolladores("SVRVIVE Studios", "@svrviveofficial"),
                New Clases.Desarrolladores("System Era Softworks", "@astroneergame"),
                New Clases.Desarrolladores("TaleWorlds Entertainment", "@Mount_and_Blade"),
                New Clases.Desarrolladores("Team17", "@Team17Ltd"),
                New Clases.Desarrolladores("Team Reptile", "@ReptileGames"),
                New Clases.Desarrolladores("teamCOIL GAMES", "@teamCOIL"),
                New Clases.Desarrolladores("Techland", "@TechlandGames"),
                New Clases.Desarrolladores("Telltale Games", "@telltalegames"),
                New Clases.Desarrolladores("Tequilabyte Studio", "@StanislavZagniy"),
                New Clases.Desarrolladores("Tero Lunkka games", "@TerhoTero"),
                New Clases.Desarrolladores("TERRI VELLMANN", "@terrivellmann"),
                New Clases.Desarrolladores("The Behemoth", "@thebehemoth"),
                New Clases.Desarrolladores("The Game Bakers", "@TheGameBakers"),
                New Clases.Desarrolladores("The Hidden Levels", "@TheHiddenLevels"),
                New Clases.Desarrolladores("The Neocore Collective", "@NeocoreGames"),
                New Clases.Desarrolladores("Thunder Lotus Games", "@ThunderLotus"),
                New Clases.Desarrolladores("Throwback Entertainment", "@ThrowbackCorp"),
                New Clases.Desarrolladores("THQ Nordic", "@THQNordic"),
                New Clases.Desarrolladores("Tin Man Games", "@TinManGames"),
                New Clases.Desarrolladores("tinyBuild", "@tinyBuild"),
                New Clases.Desarrolladores("TML-Studios", "@TMLStudios"),
                New Clases.Desarrolladores("Toge Productions", "@togeproductions"),
                New Clases.Desarrolladores("Tomorrow Corporation", "@TomorrowCorp"),
                New Clases.Desarrolladores("Total War", "@totalwar"),
                New Clases.Desarrolladores("Trendy Entertainment", "@TrendyEnt"),
                New Clases.Desarrolladores("Trese Brothers", "@TreseBrothers"),
                New Clases.Desarrolladores("Tribute Games", "@TributeGames"),
                New Clases.Desarrolladores("Tripwire Interactive", "@TripwireInt"),
                New Clases.Desarrolladores("Triumph Studios", "@TriumphStudios"),
                New Clases.Desarrolladores("Triverske", "@Triverske"),
                New Clases.Desarrolladores("Ubisoft", "@Ubisoft"),
                New Clases.Desarrolladores("UppercutGames", "@UppercutGames"),
                New Clases.Desarrolladores("Upfall Studios", "@UpfallStudios"),
                New Clases.Desarrolladores("U-PLAY Online", "@uplayonline"),
                New Clases.Desarrolladores("Valhalla Cats", "@valhallacats"),
                New Clases.Desarrolladores("VaragtP", "@VaragtP"),
                New Clases.Desarrolladores("Variable State", "@VariableState"),
                New Clases.Desarrolladores("VDOGMS", "@CallysCaves"),
                New Clases.Desarrolladores("Versus Evil", "@vs_evil"),
                New Clases.Desarrolladores("Vertigo Gaming", "@hubigans"),
                New Clases.Desarrolladores("Villa Gorilla", "@YokuGame"),
                New Clases.Desarrolladores("VisualArts/Key", "@VisualArtsUSA"),
                New Clases.Desarrolladores("Vlambeer", "@Vlambeer"),
                New Clases.Desarrolladores("VooFoo Studios", "@VooFoo"),
                New Clases.Desarrolladores("Wadjet Eye Games", "@WadjetEyeGames"),
                New Clases.Desarrolladores("Wales Interactive", "@WalesInter"),
                New Clases.Desarrolladores("Warhorse Studios", "@WarhorseStudios"),
                New Clases.Desarrolladores("Wastelands Interactive", "@WstlInteractive"),
                New Clases.Desarrolladores("WayForward", "@WayForward"),
                New Clases.Desarrolladores("Weather Factory", "@factoryweather"),
                New Clases.Desarrolladores("WeirdBeard", "@WeirdBeardGames"),
                New Clases.Desarrolladores("Wild Factor", "@WildFactorGames"),
                New Clases.Desarrolladores("Windybeard", "@WindybeardGames"),
                New Clases.Desarrolladores("Winter Wolves Games", "@pcmacgames"),
                New Clases.Desarrolladores("Wired Productions", "@WiredP"),
                New Clases.Desarrolladores("Wolcen Studio", "@WolcenGame"),
                New Clases.Desarrolladores("Wolfire Games", "@Wolfire"),
                New Clases.Desarrolladores("Wonderful Lasers", "@lasersinc"),
                New Clases.Desarrolladores("XREAL Games", "@XREALGames"),
                New Clases.Desarrolladores("XSEED Games", "@XSEEDGames"),
                New Clases.Desarrolladores("Yacht Club Games", "@YachtClubGames"),
                New Clases.Desarrolladores("Yai Gameworks", "@YaiGameworks"),
                New Clases.Desarrolladores("Yangyang Mobile", "@yangyangmobile"),
                New Clases.Desarrolladores("Young Horses", "@YoungHorses"),
                New Clases.Desarrolladores("Ysbryd Games", "@YsbrydGames"),
                New Clases.Desarrolladores("Zachtronics", "@zachtronics"),
                New Clases.Desarrolladores("Zeiva Inc", "@zeivainc"),
                New Clases.Desarrolladores("Zen Studios", "@zen_studios"),
                New Clases.Desarrolladores("Zero Gravity Games", "@playhellion"),
                New Clases.Desarrolladores("Zoink Games", "@ZoinkGames")
            }

            Return lista
        End Function

        Public Function LimpiarPublisher(publisher As String)

            Dim listaCaracteres As New List(Of String) From {"Games", "Entertainment", "Productions", "Studios", "Ltd",
                "S.L.", "LLC", "GAMES", "Inc", "Studio", "The", "LTD", "Software", "Game", "GmbH", "Softworks", "Digital",
                "Interactive",
                " ", "•", ">", "<", "¿", "?", "!", "¡", ":", ".", "_", "–", "-", ";", ",", "™", "®", "'", "´", "`",
                "(", ")", "/", "\", "|", "&", "#", "=", ChrW(34), "@", "^", "[", "]", "ª", "«"}

            For Each item In listaCaracteres
                publisher = publisher.Replace(item, Nothing)
            Next

            publisher = publisher.ToLower
            publisher = publisher.Trim

            Return publisher
        End Function

    End Module
End Namespace

