Namespace pepeizq.Editor.pepeizqdeals
    Module Publishers

        Public Sub GenerarDatos()

            Dim listaPublishers As List(Of Clases.Publishers) = CargarLista()

            Dim frame As Frame = Window.Current.Content
            Dim pagina As Page = frame.Content

            Dim cb As ComboBox = pagina.FindName("cbEditorTitulopepeizqdealsPublishers")
            cb.Items.Clear()

            cb.Items.Add("--")

            If listaPublishers.Count > 0 Then
                For Each publisher In listaPublishers
                    Dim tb As New TextBlock With {
                        .Text = publisher.Publisher,
                        .Tag = publisher.Twitter
                    }

                    cb.Items.Add(tb)
                Next
            End If

            cb.SelectedIndex = 0

            AddHandler cb.SelectionChanged, AddressOf CambiarTitulo

        End Sub

        Private Sub CambiarTitulo(sender As Object, e As SelectionChangedEventArgs)

            Dim frame As Frame = Window.Current.Content
            Dim pagina As Page = frame.Content

            Dim cb As ComboBox = sender

            Dim tbTitulo As TextBox = pagina.FindName("tbEditorTitulopepeizqdeals")

            If Not cb.SelectedIndex = 0 Then
                If Not tbTitulo.Text = Nothing Then
                    If tbTitulo.Text.Contains("Sale") Then
                        Dim publisher As TextBlock = cb.SelectedItem

                        If Not publisher Is Nothing Then
                            tbTitulo.Text = publisher.Text + " " + tbTitulo.Text
                        End If
                    End If
                End If
            End If

        End Sub

        Private Function CargarLista()

            Dim lista As New List(Of Clases.Publishers) From {
                New Clases.Publishers("10tons", "@10tonsLtd"),
                New Clases.Publishers("11 bit studios", "@11bitstudios"),
                New Clases.Publishers("1C Company", "@1C_Company"),
                New Clases.Publishers("2K", "@2K"),
                New Clases.Publishers("2 Zombie Games", "@2zombiegames"),
                New Clases.Publishers("34BigThings", "@34bigthings"),
                New Clases.Publishers("3D Avenue", "@3D_Avenue"),
                New Clases.Publishers("3DClouds.it", "@3DClouds"),
                New Clases.Publishers("505 Games", "@505_Games"),
                New Clases.Publishers("Abbey Games", "@AbbeyGamesNL"),
                New Clases.Publishers("Abylight Studios", "@abylight"),
                New Clases.Publishers("ACE Team", "@theACETeam"),
                New Clases.Publishers("Adliberum", "@liamtwose"),
                New Clases.Publishers("Adult Swim", "@adultswimgames"),
                New Clases.Publishers("Aerosoft", "@AerosoftGmbH"),
                New Clases.Publishers("Akupara Games", "@akuparagames"),
                New Clases.Publishers("Aksys Games", "@aksysgames"),
                New Clases.Publishers("ALICE IN DISSONANCE", "@projectwritten"),
                New Clases.Publishers("Alientrap", "@AlientrapGames"),
                New Clases.Publishers("Amanita Design", "@Amanita_Design"),
                New Clases.Publishers("Ammobox Studios", "@ammoboxstudios"),
                New Clases.Publishers("Amplitude Studios", "@Amplitude"),
                New Clases.Publishers("Analgesic Productions", "@analgesicprod"),
                New Clases.Publishers("Ankama", "@AnkamaGames"),
                New Clases.Publishers("Annapurna Interactive", "@A_i"),
                New Clases.Publishers("Applava", "@Applava"),
                New Clases.Publishers("Arc System Works", "@ArcSystemWorksU"),
                New Clases.Publishers("Artifex Mundi", "@ArtifexMundi"),
                New Clases.Publishers("Aspyr", "@AspyrMedia"),
                New Clases.Publishers("Atelier 801", "@Atelier801"),
                New Clases.Publishers("Atomic Fabrik", "@atomicfabrik"),
                New Clases.Publishers("Awesome Games Studio", "@AwesomeGamesStd"),
                New Clases.Publishers("Bandai Namco", "@BandaiNamcoEU"),
                New Clases.Publishers("Beamdog", "@BeamdogInc"),
                New Clases.Publishers("BeautiFun Games", "@BeautiFunGames"),
                New Clases.Publishers("Bethesda", "@bethesda"),
                New Clases.Publishers("Betadwarf", "@BetaDwarf"),
                New Clases.Publishers("Big Robot Ltd", "@BigRobotLtd"),
                New Clases.Publishers("Big Evil Corp", "@Big_Evil_Corp"),
                New Clases.Publishers("Bigben Games", "@Bigben_games"),
                New Clases.Publishers("Bitbox", "@LifeisFeudal"),
                New Clases.Publishers("Black Icicles", "@BlackIceTheGame"),
                New Clases.Publishers("Black Forest Games", "@BlackForestTeam"),
                New Clases.Publishers("BlackEye Games", "@GloriaVictisMMO"),
                New Clases.Publishers("Blacklight Interactive", "@BlackLightInt"),
                New Clases.Publishers("BlackMill Games", "@BlackMillGame"),
                New Clases.Publishers("Blazing Griffin", "@BlazingGriffin"),
                New Clases.Publishers("Blendo Games", "@BlendoGames"),
                New Clases.Publishers("Blue Isle Studios", "@BlueIsleStudio"),
                New Clases.Publishers("Bohemia Interactive", "@bohemiainteract"),
                New Clases.Publishers("Brace Yourself Games", "@BYG_Vancouver"),
                New Clases.Publishers("Brilliant Game Studios", "@BrilliantGames"),
                New Clases.Publishers("BT Studios", "@btstudiosgames"),
                New Clases.Publishers("Buka Entertainment", "@Buka_Ent_Games"),
                New Clases.Publishers("BURA", "@lgdays"),
                New Clases.Publishers("Butterscotch", "@BScotchShenani"),
                New Clases.Publishers("Capcom", "@CapcomUSA_"),
                New Clases.Publishers("Capybara Games", "@CAPYGAMES"),
                New Clases.Publishers("Carbon Games", "@CarbonGames"),
                New Clases.Publishers("Cat Nigiri", "@CatNigiri"),
                New Clases.Publishers("CCP Games", "@CCPGames"),
                New Clases.Publishers("CCCP-games", "@LeCCCP"),
                New Clases.Publishers("CD PROJEKT RED", "@CDPROJEKTRED"),
                New Clases.Publishers("Cellar Door Games", "@CellarDoorGames"),
                New Clases.Publishers("Choice of Games", "@choiceofgames"),
                New Clases.Publishers("Chucklefish", "@ChucklefishLTDs"),
                New Clases.Publishers("CI Games", "@CIGamesOfficial"),
                New Clases.Publishers("CINEMAX GAMES", "@CINEMAXGAMES"),
                New Clases.Publishers("Clapfoot", "@foxholegame"),
                New Clases.Publishers("Clever Endeavour", "@ClevEndeavGames"),
                New Clases.Publishers("Clickteam", "@Clickteam"),
                New Clases.Publishers("Cloudhead Games", "@CloudheadGames"),
                New Clases.Publishers("CoaguCo Industries", "@CoaguCo"),
                New Clases.Publishers("Cockroach Inc", "@theDreamGame"),
                New Clases.Publishers("Codemasters", "@Codemasters"),
                New Clases.Publishers("Codename Entertainment", "@CodenameEnt"),
                New Clases.Publishers("ConcernedApe", "@ConcernedApe"),
                New Clases.Publishers("Copychaser Games", "@bengelinas"),
                New Clases.Publishers("Cosmo D Studios", "@cosmoddd"),
                New Clases.Publishers("COWCAT Games", "@COWCATGames"),
                New Clases.Publishers("Crate Entertainment", "@GrimDawn"),
                New Clases.Publishers("Crazy Monkey Studios", "@CrazyMonkeyStu"),
                New Clases.Publishers("Croteam", "@Croteam"),
                New Clases.Publishers("Crows Crows Crows", "@crowsx3"),
                New Clases.Publishers("Crytivo", "@Crytivo"),
                New Clases.Publishers("Curve Digital", "@CurveDigital"),
                New Clases.Publishers("Cyan Worlds Inc", "@cyanworlds"),
                New Clases.Publishers("Cyanide Studio", "@CyanideStudio"),
                New Clases.Publishers("D-Pad Studio", "@DPadStudio"),
                New Clases.Publishers("D3 PUBLISHER", "@D3_PUBLISHER"),
                New Clases.Publishers("Daedalic", "@daedalic"),
                New Clases.Publishers("Daniel Mullins Games", "@DMullinsGames"),
                New Clases.Publishers("Daylight-Studios", "@holypotatogame"),
                New Clases.Publishers("Deadpan Games", "@onegamewill"),
                New Clases.Publishers("DECK13 Interactive", "@Deck13_de"),
                New Clases.Publishers("Deep Silver", "@deepsilver"),
                New Clases.Publishers("Degica", "@DegicaGames"),
                New Clases.Publishers("Destructive Creations", "@DestCreat_Team"),
                New Clases.Publishers("Devilish Games", "@devilishgames"),
                New Clases.Publishers("Devolver Digital", "@devolverdigital"),
                New Clases.Publishers("Digital Extremes", "@PlayWarframe"),
                New Clases.Publishers("Digitalmindsoft", "@digitalmindsoft"),
                New Clases.Publishers("Dinosaur Polo Club", "@dinopoloclub"),
                New Clases.Publishers("DireWolfDigital", "@direwolfdigital"),
                New Clases.Publishers("DLsite", "@DLsite"),
                New Clases.Publishers("Dodge Roll", "@DodgeRollGames"),
                New Clases.Publishers("Dotemu", "@Dotemu"),
                New Clases.Publishers("DoubleDutch Games", "@dd_games"),
                New Clases.Publishers("Double Eleven LTD", "@DoubleElevenLtd"),
                New Clases.Publishers("Double Fine", "@DoubleFine"),
                New Clases.Publishers("Draknek", "@Draknek"),
                New Clases.Publishers("DrinkBox Studios", "@DrinkBoxStudios"),
                New Clases.Publishers("Drool LLC", "@ThumperGame"),
                New Clases.Publishers("DRUNKEN APES GAMES", "@DrunkenApes"),
                New Clases.Publishers("DYA Games", "@DYAGames"),
                New Clases.Publishers("Egosoft", "@EGOSOFT"),
                New Clases.Publishers("Eidos Montréal", "@EidosMontreal"),
                New Clases.Publishers("Ellada Games", "@ElladaGames"),
                New Clases.Publishers("Endless Loop Studios", "@EndlessLoopStd"),
                New Clases.Publishers("EnsenaSoft", "@ensenasoft"),
                New Clases.Publishers("Eugen Systems", "@EugenSystems"),
                New Clases.Publishers("Excalibur Games", "@Excalpublishing"),
                New Clases.Publishers("Exor Studios", "@EXORStudios"),
                New Clases.Publishers("Fabraz", "@Fabrazz"),
                New Clases.Publishers("Failbetter Games", "@failbettergames"),
                New Clases.Publishers("Fantasy Grounds", "@FantasyGrounds2"),
                New Clases.Publishers("Fatshark", "@fatsharkgames"),
                New Clases.Publishers("Fellow Traveller", "@FellowTravellr"),
                New Clases.Publishers("Finji", "@FinjiCo"),
                New Clases.Publishers("Firaxis Games", "@FiraxisGames"),
                New Clases.Publishers("Firefly Studios", "@fireflyworlds"),
                New Clases.Publishers("Fireproof Games", "@Fireproof_Games"),
                New Clases.Publishers("Fishing Cactus", "@FishingCactus"),
                New Clases.Publishers("Flashbulb", "@flashbulbgames"),
                New Clases.Publishers("Focus Home", "@FocusHome"),
                New Clases.Publishers("Forgotten Empires", "@ForgottenEmp"),
                New Clases.Publishers("Freebird Games", "@Reives_Freebird"),
                New Clases.Publishers("Freejam", "@Freejamgames"),
                New Clases.Publishers("FreezeNova Games", "@FreezeNova"),
                New Clases.Publishers("Frictional Games", "@frictionalgames"),
                New Clases.Publishers("Frogwares", "@Frogwares"),
                New Clases.Publishers("Frontwing USA", "@FrontwingInt"),
                New Clases.Publishers("Frozenbyte", "@Frozenbyte"),
                New Clases.Publishers("Fruitbat Factory", "@FruitbatFactory"),
                New Clases.Publishers("Fun Bits Interactive", "@SquidsFromSpace"),
                New Clases.Publishers("Funcom", "@funcom"),
                New Clases.Publishers("Funktronic Labs", "@funktroniclabs"),
                New Clases.Publishers("Gambrinous", "@gambrinous"),
                New Clases.Publishers("Gameconnect", "@gameconnectnet"),
                New Clases.Publishers("Gamepires", "@Gamepires"),
                New Clases.Publishers("Gamera Interactive", "@gameragamesint"),
                New Clases.Publishers("Games Operators", "@GamesOperators"),
                New Clases.Publishers("Gato Salvaje S.L.", "@GatoSalvajeDEV"),
                New Clases.Publishers("GFX47 Games", "@GFX47"),
                New Clases.Publishers("Ghost Ship Games", "@JoinDeepRock"),
                New Clases.Publishers("Glaiel Games", "@TylerGlaiel"),
                New Clases.Publishers("GoblinzStudio", "@studio_goblinz"),
                New Clases.Publishers("Green Man Gaming", "@gmg_publishing"),
                New Clases.Publishers("Greenheart Games", "@GreenheartGames"),
                New Clases.Publishers("Grey Alien Games", "@GreyAlien"),
                New Clases.Publishers("Grip Digital", "@Grip_Digital"),
                New Clases.Publishers("Groupees", "@groupees1"),
                New Clases.Publishers("HakJak", "@HakJakGames"),
                New Clases.Publishers("Hammer&Ravens", "@Ham_Rav"),
                New Clases.Publishers("HandyGames", "@handy_games"),
                New Clases.Publishers("Headup Games", "@HeadupGames"),
                New Clases.Publishers("Hemisphere Games", "@HemisphereGames"),
                New Clases.Publishers("HeR Interactive", "@HerInteractive"),
                New Clases.Publishers("Hidden Path Entertainment", "@HiddenPathEnt"),
                New Clases.Publishers("Hinterland Studio", "@HinterlandGames"),
                New Clases.Publishers("Hoplon Infotainment", "@HMM_Hoplon_EN"),
                New Clases.Publishers("Humble Bundle", "@humble"),
                New Clases.Publishers("Ice-Pick Lodge", "@IcePickLodge"),
                New Clases.Publishers("Iceberg", "@Iceberg_Int"),
                New Clases.Publishers("IDALGAME", "@IDALGAME"),
                New Clases.Publishers("Idea Factory", "@IdeaFactoryIntl"),
                New Clases.Publishers("Image & Form", "@ImageForm"),
                New Clases.Publishers("Imperium42 Game Studio", "@TheThroneOfLies"),
                New Clases.Publishers("INDIECODE GAMES", "@INDIECODE_GAMES"),
                New Clases.Publishers("IndieGala", "@IndieGala"),
                New Clases.Publishers("inkle", "@inkleStudios"),
                New Clases.Publishers("Introversion Software", "@IVSoftware"),
                New Clases.Publishers("InvertMouse", "@InvertMouse"),
                New Clases.Publishers("ION LANDS", "@ionlands"),
                New Clases.Publishers("Jackbox Games", "@jackboxgames"),
                New Clases.Publishers("JAST", "@jastusa"),
                New Clases.Publishers("JForce Games", "@JForceGames"),
                New Clases.Publishers("Jolly Crouton Media", "@jollycrouton"),
                New Clases.Publishers("Jundroo", "@JundrooGames"),
                New Clases.Publishers("Kagura Games", "@KaguraGaming"),
                New Clases.Publishers("Kaleido Games", "@KaleidoGames"),
                New Clases.Publishers("Kalypso", "@kalypsomediausa"),
                New Clases.Publishers("KillHouse Games", "@inthekillhouse"),
                New Clases.Publishers("Kitfox Games", "@KitfoxGames"),
                New Clases.Publishers("Klei", "@klei"),
                New Clases.Publishers("Knuckle Cracker", "@knucracker"),
                New Clases.Publishers("Konami", "@Konami"),
                New Clases.Publishers("Konstructors Entertainment", "@konstructors"),
                New Clases.Publishers("LAME Dimension", "@ChairGTables"),
                New Clases.Publishers("Larian Studios", "@larianstudios"),
                New Clases.Publishers("League of Geeks", "@ArmelloGame"),
                New Clases.Publishers("Loren Lemcke", "@LorenLemcke"),
                New Clases.Publishers("Lince Works", "@LinceWorks"),
                New Clases.Publishers("Lucid Games Ltd", "@LucidGamesLtd"),
                New Clases.Publishers("Lupiesoft", "@Lupiesoft"),
                New Clases.Publishers("M2H", "@M2Hgames"),
                New Clases.Publishers("MangaGamer", "@MangaGamer"),
                New Clases.Publishers("Marcelo Barbosa", "@tchecoforevis"),
                New Clases.Publishers("Marmalade Game Studio", "@MarmaladeGames"),
                New Clases.Publishers("Marvelous Europe", "@marvelous_games"),
                New Clases.Publishers("Meridian4", "@Meridian4"),
                New Clases.Publishers("messhof", "@messhof"),
                New Clases.Publishers("Mi-Clos Studio", "@Mi_Clos"),
                New Clases.Publishers("Midgar Studio", "@MidgarStudio"),
                New Clases.Publishers("Might & Delight", "@MightAndDelight"),
                New Clases.Publishers("Milkstone Studios", "@milkstone"),
                New Clases.Publishers("Mimimi", "@MimimiProd"),
                New Clases.Publishers("Mode 7 Games", "@mode7games"),
                New Clases.Publishers("Modii Games", "@modiigames"),
                New Clases.Publishers("Monolith Productions", "@MonolithDev"),
                New Clases.Publishers("Monomi Park", "@monomipark"),
                New Clases.Publishers("Monstrum Games", "@monstersden"),
                New Clases.Publishers("Motion Twin", "@motiontwin"),
                New Clases.Publishers("Nadeo", "@Maniaplanet"),
                New Clases.Publishers("Ndemic Creations", "@NdemicCreations"),
                New Clases.Publishers("New Blood Interactive", "@TheNewBloods"),
                New Clases.Publishers("Night Dive Studios", "@NightdiveStudio"),
                New Clases.Publishers("Ninja Theory", "@NinjaTheory"),
                New Clases.Publishers("NIS America", "@NISAmerica"),
                New Clases.Publishers("No More Robots", "@nomorerobotshq"),
                New Clases.Publishers("Nomad Games", "@Nomadgames"),
                New Clases.Publishers("Ntroy", "@PDO2online"),
                New Clases.Publishers("Nyamyam", "@nyamyamgames"),
                New Clases.Publishers("Nyu Media", "@nyumedia"),
                New Clases.Publishers("Obsidian Entertainment", "@obsidian"),
                New Clases.Publishers("Oddworld Inhabitants", "@OddworldInc"),
                New Clases.Publishers("OhNooStudio", "@OhNooStudio"),
                New Clases.Publishers("Oliver Age 24", "@OliverAge24"),
                New Clases.Publishers("ONEVISION GAMES", "@ONEVISION_GAMES"),
                New Clases.Publishers("OrangePixel", "@OrangePixel"),
                New Clases.Publishers("Over the Top Games", "@OverTheTopGames"),
                New Clases.Publishers("Paper Castle Games", "@Underherodevs"),
                New Clases.Publishers("Paradox Development Studio", "@PDX_Dev_Studio"),
                New Clases.Publishers("Paradox Interactive", "@PdxInteractive"),
                New Clases.Publishers("Pathea Games", "@PatheaGames"),
                New Clases.Publishers("Patriot Game", "@GameOfPatriot"),
                New Clases.Publishers("Payload Studios", "@TerraTechGame"),
                New Clases.Publishers("Perfect World", "@PlayArcGames"),
                New Clases.Publishers("Piko Interactive", "@Pikointeractive"),
                New Clases.Publishers("Pirate Software", "@PirateSoftware"),
                New Clases.Publishers("PixelCount Studios", "@PixelCountGames"),
                New Clases.Publishers("Pixeljam", "@pixeljamgames"),
                New Clases.Publishers("PixelTail Games", "@PixelTailGames"),
                New Clases.Publishers("PlayFig", "@PlayFig"),
                New Clases.Publishers("PLAYISM", "@playismEN"),
                New Clases.Publishers("Pocketwatch Games", "@PocketwatchG"),
                New Clases.Publishers("Portable Moose", "@PortableMoose"),
                New Clases.Publishers("Positech Games", "@cliffski"),
                New Clases.Publishers("Powerhoof", "@Powerhoof"),
                New Clases.Publishers("Rain Games", "@rain_games"),
                New Clases.Publishers("Rat King Entertainment", "@RatKingsLair"),
                New Clases.Publishers("Raw Fury Games", "@rawfury"),
                New Clases.Publishers("Re-Logic", "@ReLogicGames"),
                New Clases.Publishers("Rebellion", "@Rebellion"),
                New Clases.Publishers("Red Barrels", "@TheRedBarrels"),
                New Clases.Publishers("Red Candle Games", "@redcandlegames"),
                New Clases.Publishers("Red Hook Studios", "@RedHookStudios"),
                New Clases.Publishers("Red Thread Games", "@RedThreadGames"),
                New Clases.Publishers("Reiza Studios", "@ReizaStudios"),
                New Clases.Publishers("Reverie World Studios", "@MedievalKW"),
                New Clases.Publishers("Ripstone", "@RipstoneGames"),
                New Clases.Publishers("Rising Star Games", "@RisingStarGames"),
                New Clases.Publishers("Robot Entertainment", "@RobotEnt"),
                New Clases.Publishers("Robotality", "@robotality"),
                New Clases.Publishers("Running With Scissors", "@RWSbleeter"),
                New Clases.Publishers("Sad Panda Studios", "@SadPandaStudio"),
                New Clases.Publishers("SakuraGame", "@SakuraGame_EN"),
                New Clases.Publishers("Sam Barlow", "@mrsambarlow"),
                New Clases.Publishers("Sauropod Studio", "@SauropodStudio"),
                New Clases.Publishers("Say Again Studio", "@manfightdragon"),
                New Clases.Publishers("SCS Software", "@SCSsoftware"),
                New Clases.Publishers("SEGA", "@SEGA"),
                New Clases.Publishers("Sekai Project", "@sekaiproject"),
                New Clases.Publishers("Senscape", "@Senscape"),
                New Clases.Publishers("SFB Games", "@SFBTom"),
                New Clases.Publishers("Shiver Games", "@shivergames"),
                New Clases.Publishers("Sigono", "@sigonogames"),
                New Clases.Publishers("SilentFuture", "@silentfuture_de"),
                New Clases.Publishers("sixteen tons", "@emergency_game"),
                New Clases.Publishers("SixtyGig Games", "@RaymondDoerr"),
                New Clases.Publishers("Ska Studios", "@skastudios"),
                New Clases.Publishers("Sludj Games", "@SludjGames"),
                New Clases.Publishers("Sluggerfly", "@SluggerflyDev"),
                New Clases.Publishers("SMG Studio", "@smgstudio"),
                New Clases.Publishers("Snail Games USA", "@SnailGamesUSA"),
                New Clases.Publishers("Snap Finger Click", "@snapfingerclick"),
                New Clases.Publishers("SnoutUp", "@SnoutUp"),
                New Clases.Publishers("SOEDESCO", "@SOEDESCO"),
                New Clases.Publishers("Spearhead Games", "@SpearheadMtl"),
                New Clases.Publishers("Spike Chunsoft", "@SpikeChunsoft_e"),
                New Clases.Publishers("Spooky Squid Games", "@spookysquid"),
                New Clases.Publishers("Square Enix", "@SquareEnix"),
                New Clases.Publishers("SRRIVERS", "@enigmaprison"),
                New Clases.Publishers("Stardock", "@Stardock"),
                New Clases.Publishers("Studio Bean", "@OneMrBean"),
                New Clases.Publishers("Studio Eres", "@rinkuhero"),
                New Clases.Publishers("Studio Wildcard", "@survivetheark"),
                New Clases.Publishers("Subset Games", "@subsetgames"),
                New Clases.Publishers("Sukeban Games", "@SukebanGames"),
                New Clases.Publishers("Supergiant Games", "@SupergiantGames"),
                New Clases.Publishers("SureAI", "@SureAITeam"),
                New Clases.Publishers("Surprise Attack", "@FellowTravellr"),
                New Clases.Publishers("Suspicious Developments", "@Pentadact"),
                New Clases.Publishers("SVRVIVE Studios", "@svrviveofficial"),
                New Clases.Publishers("System Era Softworks", "@astroneergame"),
                New Clases.Publishers("TaleWorlds Entertainment", "@Mount_and_Blade"),
                New Clases.Publishers("Team17", "@Team17Ltd"),
                New Clases.Publishers("Team Reptile", "@ReptileGames"),
                New Clases.Publishers("Techland", "@TechlandGames"),
                New Clases.Publishers("Telltale Games", "@telltalegames"),
                New Clases.Publishers("Tero Lunkka games", "@TerhoTero"),
                New Clases.Publishers("The Behemoth", "@thebehemoth"),
                New Clases.Publishers("The Game Bakers", "@TheGameBakers"),
                New Clases.Publishers("The Hidden Levels", "@TheHiddenLevels"),
                New Clases.Publishers("The Neocore Collective", "@NeocoreGames"),
                New Clases.Publishers("Thunder Lotus Games", "@ThunderLotus"),
                New Clases.Publishers("Throwback Entertainment", "@ThrowbackCorp"),
                New Clases.Publishers("THQ Nordic", "@THQNordic"),
                New Clases.Publishers("Tin Man Games", "@TinManGames"),
                New Clases.Publishers("tinyBuild", "@tinyBuild"),
                New Clases.Publishers("TML-Studios", "@TMLStudios"),
                New Clases.Publishers("Toge Productions", "@togeproductions"),
                New Clases.Publishers("Tomorrow Corporation", "@TomorrowCorp"),
                New Clases.Publishers("Total War", "@totalwar"),
                New Clases.Publishers("Trendy Entertainment", "@TrendyEnt"),
                New Clases.Publishers("Tribute Games", "@TributeGames"),
                New Clases.Publishers("Tripwire Interactive", "@TripwireInt"),
                New Clases.Publishers("Triumph Studios", "@TriumphStudios"),
                New Clases.Publishers("Triverske", "@Triverske"),
                New Clases.Publishers("Ubisoft", "@Ubisoft"),
                New Clases.Publishers("UppercutGames", "@UppercutGames"),
                New Clases.Publishers("Upfall Studios", "@UpfallStudios"),
                New Clases.Publishers("U-PLAY Online", "@uplayonline"),
                New Clases.Publishers("Valhalla Cats", "@valhallacats"),
                New Clases.Publishers("VaragtP", "@VaragtP"),
                New Clases.Publishers("Versus Evil", "@vs_evil"),
                New Clases.Publishers("Vertigo Gaming", "@hubigans"),
                New Clases.Publishers("VisualArts/Key", "@VisualArtsUSA"),
                New Clases.Publishers("Vlambeer", "@Vlambeer"),
                New Clases.Publishers("VooFoo Studios", "@VooFoo"),
                New Clases.Publishers("Wadjet Eye Games", "@WadjetEyeGames"),
                New Clases.Publishers("Wales Interactive", "@WalesInter"),
                New Clases.Publishers("Warhorse Studios", "@WarhorseStudios"),
                New Clases.Publishers("WayForward", "@WayForward"),
                New Clases.Publishers("Weather Factory", "@factoryweather"),
                New Clases.Publishers("Windybeard", "@WindybeardGames"),
                New Clases.Publishers("Winter Wolves Games", "@pcmacgames"),
                New Clases.Publishers("Wired Productions", "@WiredP"),
                New Clases.Publishers("Wolcen Studio", "@WolcenGame"),
                New Clases.Publishers("Wolfire Games", "@Wolfire"),
                New Clases.Publishers("XREAL Games", "@XREALGames"),
                New Clases.Publishers("XSEED Games", "@XSEEDGames"),
                New Clases.Publishers("Yacht Club Games", "@YachtClubGames"),
                New Clases.Publishers("Yai Gameworks", "@YaiGameworks"),
                New Clases.Publishers("Young Horses", "@YoungHorses"),
                New Clases.Publishers("Zachtronics", "@zachtronics"),
                New Clases.Publishers("Zeiva Inc", "@zeivainc"),
                New Clases.Publishers("Zen Studios", "@zen_studios"),
                New Clases.Publishers("Zoink Games", "@ZoinkGames")
            }

            Return lista
        End Function

        Public Function LimpiarPublisher(publisher As String)

            Dim listaCaracteres As New List(Of String) From {"Games", "Entertainment", "Productions", "Studios", "Ltd",
                "S.L.", "LLC", "GAMES", "Inc", "Studio", "The", "LTD", "Software", "Game", "GmbH", "Softworks", "Digital",
                "Interactive",
                " ", "•", ">", "<", "¿", "?", "!", "¡", ":", ".", "_", "–", "-", ";", ",", "™", "®", "'", "´", "`",
                "(", ")", "/", "\", "|", "&", "#", "=", ChrW(34), "@", "^", "[", "]", "ª", "«"}

            For Each item In listaCaracteres
                publisher = publisher.Replace(item, Nothing)
            Next

            publisher = publisher.ToLower
            publisher = publisher.Trim

            Return publisher
        End Function

    End Module
End Namespace

